# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Fri Feb 06 12:17:06 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design cic

create_clock -name "clk" -period 100.0 -waveform {0.0 50.0} [get_ports clk]
set_false_path -from [get_ports rst] -to [list \
  [get_cells {d_comb_reg[1][1][0]}]  \
  [get_cells {d_comb_reg[2][1][19]}]  \
  [get_cells {d_comb_reg[1][1][19]}]  \
  [get_cells {d_comb_reg[2][1][0]}]  \
  [get_cells {d_comb_reg[0][1][0]}]  \
  [get_cells {d_comb_reg[0][1][19]}]  \
  [get_cells {d_comb_reg[0][0][2]}]  \
  [get_cells {d_comb_reg[0][0][3]}]  \
  [get_cells {d_comb_reg[0][0][4]}]  \
  [get_cells {d_comb_reg[0][0][5]}]  \
  [get_cells {d_comb_reg[0][0][6]}]  \
  [get_cells {d_comb_reg[0][0][7]}]  \
  [get_cells {d_comb_reg[0][0][8]}]  \
  [get_cells {d_comb_reg[0][0][9]}]  \
  [get_cells {d_comb_reg[0][0][10]}]  \
  [get_cells {d_comb_reg[0][0][11]}]  \
  [get_cells {d_comb_reg[0][0][12]}]  \
  [get_cells {d_comb_reg[0][0][13]}]  \
  [get_cells {d_comb_reg[0][0][14]}]  \
  [get_cells {d_comb_reg[0][0][0]}]  \
  [get_cells {d_comb_reg[0][0][17]}]  \
  [get_cells {d_comb_reg[0][0][18]}]  \
  [get_cells {d_comb_reg[0][0][1]}]  \
  [get_cells {d_comb_reg[0][0][19]}]  \
  [get_cells {d_comb_reg[0][0][15]}]  \
  [get_cells {d_comb_reg[0][0][16]}]  \
  [get_cells {d_tmp_reg[18]}]  \
  [get_cells {d_tmp_reg[14]}]  \
  [get_cells {d_tmp_reg[6]}]  \
  [get_cells {d_tmp_reg[1]}]  \
  [get_cells {d_tmp_reg[2]}]  \
  [get_cells {d_tmp_reg[3]}]  \
  [get_cells {d_tmp_reg[4]}]  \
  [get_cells {d_tmp_reg[5]}]  \
  [get_cells {d_tmp_reg[7]}]  \
  [get_cells {d_tmp_reg[8]}]  \
  [get_cells {d_tmp_reg[9]}]  \
  [get_cells {d_tmp_reg[10]}]  \
  [get_cells {d_tmp_reg[11]}]  \
  [get_cells {d_tmp_reg[12]}]  \
  [get_cells {d_tmp_reg[13]}]  \
  [get_cells {d_tmp_reg[15]}]  \
  [get_cells {d_tmp_reg[16]}]  \
  [get_cells {d_tmp_reg[17]}]  \
  [get_cells {d_tmp_reg[19]}]  \
  [get_cells RC_CG_HIER_INST3/enl_reg]  \
  [get_cells {integrator_reg[0][17]}]  \
  [get_cells {integrator_reg[0][1]}]  \
  [get_cells {integrator_reg[0][2]}]  \
  [get_cells {integrator_reg[0][3]}]  \
  [get_cells {integrator_reg[0][4]}]  \
  [get_cells {integrator_reg[3][15]}]  \
  [get_cells {integrator_reg[0][5]}]  \
  [get_cells {integrator_reg[0][6]}]  \
  [get_cells {integrator_reg[0][7]}]  \
  [get_cells {integrator_reg[3][11]}]  \
  [get_cells {integrator_reg[0][8]}]  \
  [get_cells {integrator_reg[0][9]}]  \
  [get_cells {integrator_reg[0][10]}]  \
  [get_cells {integrator_reg[3][7]}]  \
  [get_cells {integrator_reg[0][11]}]  \
  [get_cells {integrator_reg[0][12]}]  \
  [get_cells {integrator_reg[0][13]}]  \
  [get_cells {integrator_reg[0][14]}]  \
  [get_cells {integrator_reg[0][15]}]  \
  [get_cells {integrator_reg[0][16]}]  \
  [get_cells {integrator_reg[0][0]}]  \
  [get_cells {integrator_reg[2][19]}]  \
  [get_cells {integrator_reg[0][18]}]  \
  [get_cells {integrator_reg[0][19]}]  \
  [get_cells {integrator_reg[1][0]}]  \
  [get_cells {integrator_reg[2][15]}]  \
  [get_cells {integrator_reg[1][1]}]  \
  [get_cells {integrator_reg[1][2]}]  \
  [get_cells {integrator_reg[1][3]}]  \
  [get_cells {integrator_reg[2][11]}]  \
  [get_cells {integrator_reg[1][4]}]  \
  [get_cells {integrator_reg[1][5]}]  \
  [get_cells {integrator_reg[1][6]}]  \
  [get_cells {integrator_reg[1][7]}]  \
  [get_cells {integrator_reg[1][8]}]  \
  [get_cells {integrator_reg[1][9]}]  \
  [get_cells {integrator_reg[1][10]}]  \
  [get_cells {integrator_reg[2][3]}]  \
  [get_cells {integrator_reg[1][11]}]  \
  [get_cells {integrator_reg[1][12]}]  \
  [get_cells {integrator_reg[2][16]}]  \
  [get_cells {integrator_reg[1][14]}]  \
  [get_cells {integrator_reg[1][15]}]  \
  [get_cells {integrator_reg[1][16]}]  \
  [get_cells {integrator_reg[1][17]}]  \
  [get_cells {integrator_reg[1][18]}]  \
  [get_cells {integrator_reg[1][19]}]  \
  [get_cells {integrator_reg[2][0]}]  \
  [get_cells {integrator_reg[2][1]}]  \
  [get_cells {integrator_reg[2][2]}]  \
  [get_cells {integrator_reg[2][4]}]  \
  [get_cells {integrator_reg[2][5]}]  \
  [get_cells {integrator_reg[2][6]}]  \
  [get_cells {integrator_reg[2][7]}]  \
  [get_cells {integrator_reg[2][8]}]  \
  [get_cells {integrator_reg[2][9]}]  \
  [get_cells {integrator_reg[2][10]}]  \
  [get_cells {integrator_reg[2][12]}]  \
  [get_cells {integrator_reg[2][13]}]  \
  [get_cells {integrator_reg[2][14]}]  \
  [get_cells {integrator_reg[1][13]}]  \
  [get_cells {integrator_reg[2][17]}]  \
  [get_cells {integrator_reg[2][18]}]  \
  [get_cells {integrator_reg[3][0]}]  \
  [get_cells {integrator_reg[3][1]}]  \
  [get_cells {integrator_reg[3][2]}]  \
  [get_cells {integrator_reg[3][3]}]  \
  [get_cells {integrator_reg[3][4]}]  \
  [get_cells {integrator_reg[3][5]}]  \
  [get_cells {integrator_reg[3][6]}]  \
  [get_cells {integrator_reg[3][8]}]  \
  [get_cells {integrator_reg[3][9]}]  \
  [get_cells {integrator_reg[3][10]}]  \
  [get_cells {integrator_reg[3][12]}]  \
  [get_cells {integrator_reg[3][13]}]  \
  [get_cells {integrator_reg[3][14]}]  \
  [get_cells {integrator_reg[3][16]}]  \
  [get_cells {integrator_reg[3][17]}]  \
  [get_cells {integrator_reg[3][18]}]  \
  [get_cells {integrator_reg[3][19]}]  \
  [get_cells {d_comb_reg[1][0][0]}]  \
  [get_cells {d_comb_reg[1][0][1]}]  \
  [get_cells {d_comb_reg[1][0][2]}]  \
  [get_cells {d_comb_reg[1][0][3]}]  \
  [get_cells {d_comb_reg[1][0][4]}]  \
  [get_cells {d_comb_reg[1][0][5]}]  \
  [get_cells {d_comb_reg[1][0][6]}]  \
  [get_cells {d_comb_reg[1][0][7]}]  \
  [get_cells {d_comb_reg[1][0][8]}]  \
  [get_cells {d_comb_reg[1][0][9]}]  \
  [get_cells {d_comb_reg[1][0][10]}]  \
  [get_cells {d_comb_reg[1][0][11]}]  \
  [get_cells {d_comb_reg[1][0][12]}]  \
  [get_cells {d_comb_reg[1][0][13]}]  \
  [get_cells {d_comb_reg[1][0][14]}]  \
  [get_cells {d_comb_reg[1][0][15]}]  \
  [get_cells {d_comb_reg[1][0][16]}]  \
  [get_cells {d_comb_reg[1][0][17]}]  \
  [get_cells {d_comb_reg[1][0][18]}]  \
  [get_cells {d_comb_reg[1][0][19]}]  \
  [get_cells {d_comb_reg[2][0][0]}]  \
  [get_cells {d_comb_reg[2][0][1]}]  \
  [get_cells {d_comb_reg[2][0][2]}]  \
  [get_cells {d_comb_reg[2][0][3]}]  \
  [get_cells {d_comb_reg[2][0][4]}]  \
  [get_cells {d_comb_reg[2][0][5]}]  \
  [get_cells {d_comb_reg[2][0][6]}]  \
  [get_cells {d_comb_reg[2][0][7]}]  \
  [get_cells {d_comb_reg[2][0][8]}]  \
  [get_cells {d_comb_reg[2][0][9]}]  \
  [get_cells {d_comb_reg[2][0][10]}]  \
  [get_cells {d_comb_reg[2][0][11]}]  \
  [get_cells {d_comb_reg[2][0][12]}]  \
  [get_cells {d_comb_reg[2][0][13]}]  \
  [get_cells {d_comb_reg[2][0][14]}]  \
  [get_cells {d_comb_reg[2][0][15]}]  \
  [get_cells {d_comb_reg[2][0][16]}]  \
  [get_cells {d_comb_reg[2][0][17]}]  \
  [get_cells {d_comb_reg[2][0][18]}]  \
  [get_cells {d_comb_reg[2][0][19]}]  \
  [get_cells {d_comb_reg[3][0][0]}]  \
  [get_cells {d_comb_reg[3][0][1]}]  \
  [get_cells {d_comb_reg[3][0][2]}]  \
  [get_cells {d_comb_reg[3][0][3]}]  \
  [get_cells {d_comb_reg[3][0][4]}]  \
  [get_cells {d_comb_reg[3][0][5]}]  \
  [get_cells {d_comb_reg[3][0][6]}]  \
  [get_cells {d_comb_reg[3][0][7]}]  \
  [get_cells {d_comb_reg[3][0][8]}]  \
  [get_cells {d_comb_reg[3][0][9]}]  \
  [get_cells {d_comb_reg[3][0][10]}]  \
  [get_cells {d_comb_reg[3][0][11]}]  \
  [get_cells {d_comb_reg[3][0][12]}]  \
  [get_cells {d_comb_reg[3][0][13]}]  \
  [get_cells {d_comb_reg[3][0][14]}]  \
  [get_cells {d_comb_reg[3][0][15]}]  \
  [get_cells {d_comb_reg[3][0][16]}]  \
  [get_cells {d_comb_reg[3][0][17]}]  \
  [get_cells {d_comb_reg[3][0][18]}]  \
  [get_cells {d_comb_reg[3][0][19]}]  \
  [get_cells {d_comb_reg[3][1][0]}]  \
  [get_cells {d_comb_reg[3][1][1]}]  \
  [get_cells {d_comb_reg[3][1][2]}]  \
  [get_cells {d_comb_reg[3][1][3]}]  \
  [get_cells {d_comb_reg[3][1][4]}]  \
  [get_cells {d_comb_reg[3][1][5]}]  \
  [get_cells {d_comb_reg[3][1][6]}]  \
  [get_cells {d_comb_reg[3][1][7]}]  \
  [get_cells {d_comb_reg[3][1][8]}]  \
  [get_cells {d_comb_reg[3][1][9]}]  \
  [get_cells {d_comb_reg[3][1][10]}]  \
  [get_cells {d_comb_reg[3][1][11]}]  \
  [get_cells {d_comb_reg[3][1][12]}]  \
  [get_cells {d_comb_reg[3][1][13]}]  \
  [get_cells {d_comb_reg[3][1][14]}]  \
  [get_cells {d_comb_reg[3][1][15]}]  \
  [get_cells {d_comb_reg[3][1][16]}]  \
  [get_cells {d_comb_reg[3][1][17]}]  \
  [get_cells {d_comb_reg[3][1][18]}]  \
  [get_cells {d_comb_reg[3][1][19]}]  \
  [get_cells RC_CG_HIER_INST2/enl_reg]  \
  [get_cells RC_CG_HIER_INST1/enl_reg]  \
  [get_cells {d_comb_reg[2][1][1]}]  \
  [get_cells {d_comb_reg[2][1][14]}]  \
  [get_cells {d_comb_reg[2][1][7]}]  \
  [get_cells {d_comb_reg[2][1][13]}]  \
  [get_cells {d_comb_reg[2][1][17]}]  \
  [get_cells {d_comb_reg[2][1][9]}]  \
  [get_cells {d_comb_reg[2][1][11]}]  \
  [get_cells {d_comb_reg[2][1][12]}]  \
  [get_cells {d_comb_reg[2][1][6]}]  \
  [get_cells {d_comb_reg[2][1][3]}]  \
  [get_cells {d_comb_reg[2][1][16]}]  \
  [get_cells {d_comb_reg[2][1][8]}]  \
  [get_cells {d_comb_reg[2][1][18]}]  \
  [get_cells {d_comb_reg[2][1][15]}]  \
  [get_cells {d_comb_reg[2][1][10]}]  \
  [get_cells {d_comb_reg[2][1][2]}]  \
  [get_cells {d_comb_reg[2][1][4]}]  \
  [get_cells {d_comb_reg[2][1][5]}]  \
  [get_cells {d_comb_reg[1][1][1]}]  \
  [get_cells {d_comb_reg[1][1][14]}]  \
  [get_cells {d_comb_reg[1][1][7]}]  \
  [get_cells {d_comb_reg[1][1][13]}]  \
  [get_cells {d_comb_reg[1][1][17]}]  \
  [get_cells {d_comb_reg[1][1][9]}]  \
  [get_cells {d_comb_reg[1][1][11]}]  \
  [get_cells {d_comb_reg[1][1][12]}]  \
  [get_cells {d_comb_reg[1][1][6]}]  \
  [get_cells {d_comb_reg[1][1][3]}]  \
  [get_cells {d_comb_reg[1][1][16]}]  \
  [get_cells {d_comb_reg[1][1][8]}]  \
  [get_cells {d_comb_reg[1][1][18]}]  \
  [get_cells {d_comb_reg[1][1][15]}]  \
  [get_cells {d_comb_reg[1][1][10]}]  \
  [get_cells {d_comb_reg[1][1][2]}]  \
  [get_cells {d_comb_reg[1][1][4]}]  \
  [get_cells {d_comb_reg[1][1][5]}]  \
  [get_cells {d_comb_reg[0][1][1]}]  \
  [get_cells {d_comb_reg[0][1][14]}]  \
  [get_cells {d_comb_reg[0][1][7]}]  \
  [get_cells {d_comb_reg[0][1][13]}]  \
  [get_cells {d_comb_reg[0][1][17]}]  \
  [get_cells {d_comb_reg[0][1][9]}]  \
  [get_cells {d_comb_reg[0][1][11]}]  \
  [get_cells {d_comb_reg[0][1][12]}]  \
  [get_cells {d_comb_reg[0][1][6]}]  \
  [get_cells {d_comb_reg[0][1][3]}]  \
  [get_cells {d_comb_reg[0][1][16]}]  \
  [get_cells {d_tmp_reg[0]}]  \
  [get_cells {d_comb_reg[0][1][8]}]  \
  [get_cells {d_comb_reg[0][1][18]}]  \
  [get_cells {d_comb_reg[0][1][15]}]  \
  [get_cells {d_comb_reg[0][1][10]}]  \
  [get_cells {d_comb_reg[0][1][2]}]  \
  [get_cells {d_comb_reg[0][1][4]}]  \
  [get_cells {d_comb_reg[0][1][5]}] ]
group_path -weight 1.000000 -name cg_enable_group_clk -through [list \
  [get_pins RC_CG_HIER_INST1/enable]  \
  [get_pins RC_CG_HIER_INST2/enable]  \
  [get_pins RC_CG_HIER_INST3/enable]  \
  [get_pins RC_CG_HIER_INST1/enable]  \
  [get_pins RC_CG_HIER_INST2/enable]  \
  [get_pins RC_CG_HIER_INST3/enable]  \
  [get_pins RC_CG_HIER_INST1/enable]  \
  [get_pins RC_CG_HIER_INST2/enable]  \
  [get_pins RC_CG_HIER_INST3/enable] ]
set_clock_gating_check -setup 0.0 
