
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb  6 2026 12:17:06 IST (Feb  6 2026 06:47:06 UTC)

// Verification Directory fv/cic 

module RC_CG_MOD_AUTO_cic(ck_in, enable, test, ck_out);
  input ck_in, enable, test;
  output ck_out;
  wire ck_in, enable, test;
  wire ck_out;
  wire UNCONNECTED, enl, n_0;
  TLATNX1 enl_reg(.GN (ck_in), .D (n_0), .Q (enl), .QN (UNCONNECTED));
  OR2X1 g11__2398(.A (enable), .B (test), .Y (n_0));
  AND2X1 g17__5107(.A (enl), .B (ck_in), .Y (ck_out));
endmodule

module RC_CG_MOD_AUTO_cic_1(ck_in, enable, test, ck_out);
  input ck_in, enable, test;
  output ck_out;
  wire ck_in, enable, test;
  wire ck_out;
  wire UNCONNECTED0, enl, n_0;
  TLATNX1 enl_reg(.GN (ck_in), .D (n_0), .Q (enl), .QN (UNCONNECTED0));
  OR2X1 g11__6260(.A (enable), .B (test), .Y (n_0));
  AND2X1 g17__4319(.A (enl), .B (ck_in), .Y (ck_out));
endmodule

module RC_CG_MOD_AUTO_cic_2(ck_in, enable, test, ck_out);
  input ck_in, enable, test;
  output ck_out;
  wire ck_in, enable, test;
  wire ck_out;
  wire UNCONNECTED1, enl, n_0;
  TLATNX1 enl_reg(.GN (ck_in), .D (n_0), .Q (enl), .QN (UNCONNECTED1));
  OR2X1 g11__8428(.A (enable), .B (test), .Y (n_0));
  AND2X1 g17__5526(.A (enl), .B (ck_in), .Y (ck_out));
endmodule

module cic(clk, rst, d_in, ce_1, ce_2, d_out);
  input clk, rst, ce_1, ce_2;
  input [3:0] d_in;
  output [3:0] d_out;
  wire clk, rst, ce_1, ce_2;
  wire [3:0] d_in;
  wire [3:0] d_out;
  wire [19:0] \comb[0] ;
  wire [19:0] \d_comb[1][0] ;
  wire [19:0] \comb[1] ;
  wire [19:0] \d_comb[2][0] ;
  wire [19:0] \comb[2] ;
  wire [19:0] \d_comb[3][0] ;
  wire [19:0] \d_comb[3][1] ;
  wire [19:0] \d_comb[0][0] ;
  wire [19:0] \d_comb[0][1] ;
  wire [19:0] d_tmp;
  wire [19:0] \integrator[3] ;
  wire [19:0] \integrator[0] ;
  wire [19:0] \integrator[2] ;
  wire [19:0] \integrator[1] ;
  wire [19:0] \d_comb[1][1] ;
  wire [19:0] \d_comb[2][1] ;
  wire ADD_TC_OP_1_n_0, ADD_TC_OP_1_n_2, ADD_TC_OP_1_n_4,
       ADD_TC_OP_1_n_6, ADD_TC_OP_1_n_8, ADD_TC_OP_1_n_10,
       ADD_TC_OP_1_n_12, ADD_TC_OP_1_n_14;
  wire ADD_TC_OP_1_n_16, ADD_TC_OP_1_n_18, ADD_TC_OP_1_n_20,
       ADD_TC_OP_1_n_22, ADD_TC_OP_1_n_24, ADD_TC_OP_1_n_26,
       ADD_TC_OP_1_n_28, ADD_TC_OP_1_n_30;
  wire ADD_TC_OP_1_n_32, ADD_TC_OP_1_n_34, ADD_TC_OP_1_n_36,
       ADD_TC_OP_2_n_0, ADD_TC_OP_2_n_2, ADD_TC_OP_2_n_4,
       ADD_TC_OP_2_n_6, ADD_TC_OP_2_n_8;
  wire ADD_TC_OP_2_n_10, ADD_TC_OP_2_n_12, ADD_TC_OP_2_n_14,
       ADD_TC_OP_2_n_16, ADD_TC_OP_2_n_18, ADD_TC_OP_2_n_20,
       ADD_TC_OP_2_n_22, ADD_TC_OP_2_n_24;
  wire ADD_TC_OP_2_n_26, ADD_TC_OP_2_n_28, ADD_TC_OP_2_n_30,
       ADD_TC_OP_2_n_32, ADD_TC_OP_2_n_34, ADD_TC_OP_2_n_36,
       ADD_TC_OP_3_n_0, ADD_TC_OP_3_n_2;
  wire ADD_TC_OP_3_n_4, ADD_TC_OP_3_n_6, ADD_TC_OP_3_n_8,
       ADD_TC_OP_3_n_10, ADD_TC_OP_3_n_12, ADD_TC_OP_3_n_14,
       ADD_TC_OP_3_n_16, ADD_TC_OP_3_n_18;
  wire ADD_TC_OP_3_n_20, ADD_TC_OP_3_n_22, ADD_TC_OP_3_n_24,
       ADD_TC_OP_3_n_26, ADD_TC_OP_3_n_28, ADD_TC_OP_3_n_30,
       ADD_TC_OP_3_n_32, ADD_TC_OP_3_n_34;
  wire ADD_TC_OP_3_n_36, ADD_TC_OP_n_0, ADD_TC_OP_n_2, ADD_TC_OP_n_4,
       ADD_TC_OP_n_6, ADD_TC_OP_n_8, ADD_TC_OP_n_10, ADD_TC_OP_n_12;
  wire ADD_TC_OP_n_14, ADD_TC_OP_n_16, ADD_TC_OP_n_18, ADD_TC_OP_n_20,
       ADD_TC_OP_n_22, ADD_TC_OP_n_24, ADD_TC_OP_n_26, ADD_TC_OP_n_28;
  wire ADD_TC_OP_n_30, ADD_TC_OP_n_32, ADD_TC_OP_n_34, ADD_TC_OP_n_36,
       UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5;
  wire UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9,
       UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, n_0;
  wire n_3, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_60;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire rc_gclk, rc_gclk_1227, rc_gclk_1229, sub_72_24_n_0,
       sub_72_24_n_1, sub_72_24_n_2, sub_72_24_n_3, sub_72_24_n_4;
  wire sub_72_24_n_5, sub_72_24_n_6, sub_72_24_n_7, sub_72_24_n_8,
       sub_72_24_n_9, sub_72_24_n_10, sub_72_24_n_11, sub_72_24_n_12;
  wire sub_72_24_n_13, sub_72_24_n_14, sub_72_24_n_15, sub_72_24_n_16,
       sub_72_24_n_17, sub_72_24_n_18, sub_72_24_n_19, sub_72_24_n_21;
  wire sub_72_24_n_23, sub_72_24_n_25, sub_72_24_n_27, sub_72_24_n_29,
       sub_72_24_n_31, sub_72_24_n_33, sub_72_24_n_35, sub_72_24_n_37;
  wire sub_72_24_n_39, sub_72_24_n_41, sub_72_24_n_43, sub_72_24_n_45,
       sub_72_24_n_47, sub_72_24_n_49, sub_72_24_n_51, sub_72_24_n_53;
  wire sub_72_24_n_55, sub_75_30_I1_n_655, sub_75_30_I1_n_657,
       sub_75_30_I1_n_659, sub_75_30_I1_n_661, sub_75_30_I1_n_663,
       sub_75_30_I1_n_665, sub_75_30_I1_n_667;
  wire sub_75_30_I1_n_669, sub_75_30_I1_n_671, sub_75_30_I1_n_673,
       sub_75_30_I1_n_675, sub_75_30_I1_n_677, sub_75_30_I1_n_679,
       sub_75_30_I1_n_681, sub_75_30_I1_n_683;
  wire sub_75_30_I1_n_685, sub_75_30_I1_n_687, sub_75_30_I1_n_689,
       sub_75_30_I1_n_692, sub_75_30_I1_n_695, sub_75_30_I1_n_696,
       sub_75_30_I1_n_698, sub_75_30_I1_n_699;
  wire sub_75_30_I1_n_700, sub_75_30_I1_n_701, sub_75_30_I1_n_702,
       sub_75_30_I1_n_703, sub_75_30_I1_n_704, sub_75_30_I1_n_705,
       sub_75_30_I1_n_706, sub_75_30_I1_n_707;
  wire sub_75_30_I1_n_708, sub_75_30_I1_n_709, sub_75_30_I1_n_710,
       sub_75_30_I1_n_711, sub_75_30_I1_n_712, sub_75_30_I1_n_713,
       sub_75_30_I1_n_714, sub_75_30_I2_n_655;
  wire sub_75_30_I2_n_657, sub_75_30_I2_n_659, sub_75_30_I2_n_661,
       sub_75_30_I2_n_663, sub_75_30_I2_n_665, sub_75_30_I2_n_667,
       sub_75_30_I2_n_669, sub_75_30_I2_n_671;
  wire sub_75_30_I2_n_673, sub_75_30_I2_n_675, sub_75_30_I2_n_677,
       sub_75_30_I2_n_679, sub_75_30_I2_n_681, sub_75_30_I2_n_683,
       sub_75_30_I2_n_685, sub_75_30_I2_n_687;
  wire sub_75_30_I2_n_689, sub_75_30_I2_n_692, sub_75_30_I2_n_695,
       sub_75_30_I2_n_696, sub_75_30_I2_n_698, sub_75_30_I2_n_699,
       sub_75_30_I2_n_700, sub_75_30_I2_n_701;
  wire sub_75_30_I2_n_702, sub_75_30_I2_n_703, sub_75_30_I2_n_704,
       sub_75_30_I2_n_705, sub_75_30_I2_n_706, sub_75_30_I2_n_707,
       sub_75_30_I2_n_708, sub_75_30_I2_n_709;
  wire sub_75_30_I2_n_710, sub_75_30_I2_n_711, sub_75_30_I2_n_712,
       sub_75_30_I2_n_713, sub_75_30_I2_n_714;
  RC_CG_MOD_AUTO_cic RC_CG_HIER_INST1(.ck_in (clk), .enable (ce_2),
       .test (1'b0), .ck_out (rc_gclk));
  RC_CG_MOD_AUTO_cic_1 RC_CG_HIER_INST2(.ck_in (clk), .enable (ce_1),
       .test (1'b0), .ck_out (rc_gclk_1227));
  RC_CG_MOD_AUTO_cic_2 RC_CG_HIER_INST3(.ck_in (clk), .enable (n_60),
       .test (1'b0), .ck_out (rc_gclk_1229));
  DFFRHQXL \d_comb_reg[1][0][0] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [0]), .Q (\d_comb[1][0] [0]));
  DFFRHQXL \d_comb_reg[1][0][1] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [1]), .Q (\d_comb[1][0] [1]));
  DFFRHQXL \d_comb_reg[1][0][2] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [2]), .Q (\d_comb[1][0] [2]));
  DFFRHQXL \d_comb_reg[1][0][3] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [3]), .Q (\d_comb[1][0] [3]));
  DFFRHQXL \d_comb_reg[1][0][4] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [4]), .Q (\d_comb[1][0] [4]));
  DFFRHQXL \d_comb_reg[1][0][5] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [5]), .Q (\d_comb[1][0] [5]));
  DFFRHQXL \d_comb_reg[1][0][6] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [6]), .Q (\d_comb[1][0] [6]));
  DFFRHQXL \d_comb_reg[1][0][7] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [7]), .Q (\d_comb[1][0] [7]));
  DFFRHQXL \d_comb_reg[1][0][8] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [8]), .Q (\d_comb[1][0] [8]));
  DFFRHQXL \d_comb_reg[1][0][9] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [9]), .Q (\d_comb[1][0] [9]));
  DFFRHQXL \d_comb_reg[1][0][10] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [10]), .Q (\d_comb[1][0] [10]));
  DFFRHQXL \d_comb_reg[1][0][11] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [11]), .Q (\d_comb[1][0] [11]));
  DFFRHQXL \d_comb_reg[1][0][12] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [12]), .Q (\d_comb[1][0] [12]));
  DFFRHQXL \d_comb_reg[1][0][13] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [13]), .Q (\d_comb[1][0] [13]));
  DFFRHQXL \d_comb_reg[1][0][14] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [14]), .Q (\d_comb[1][0] [14]));
  DFFRHQXL \d_comb_reg[1][0][15] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [15]), .Q (\d_comb[1][0] [15]));
  DFFRHQXL \d_comb_reg[1][0][16] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [16]), .Q (\d_comb[1][0] [16]));
  DFFRHQXL \d_comb_reg[1][0][17] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [17]), .Q (\d_comb[1][0] [17]));
  DFFRHQXL \d_comb_reg[1][0][18] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [18]), .Q (\d_comb[1][0] [18]));
  DFFRHQXL \d_comb_reg[1][0][19] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[0] [19]), .Q (\d_comb[1][0] [19]));
  DFFRHQXL \d_comb_reg[2][0][0] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [0]), .Q (\d_comb[2][0] [0]));
  DFFRHQXL \d_comb_reg[2][0][1] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [1]), .Q (\d_comb[2][0] [1]));
  DFFRHQXL \d_comb_reg[2][0][2] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [2]), .Q (\d_comb[2][0] [2]));
  DFFRHQXL \d_comb_reg[2][0][3] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [3]), .Q (\d_comb[2][0] [3]));
  DFFRHQXL \d_comb_reg[2][0][4] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [4]), .Q (\d_comb[2][0] [4]));
  DFFRHQXL \d_comb_reg[2][0][5] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [5]), .Q (\d_comb[2][0] [5]));
  DFFRHQXL \d_comb_reg[2][0][6] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [6]), .Q (\d_comb[2][0] [6]));
  DFFRHQXL \d_comb_reg[2][0][7] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [7]), .Q (\d_comb[2][0] [7]));
  DFFRHQXL \d_comb_reg[2][0][8] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [8]), .Q (\d_comb[2][0] [8]));
  DFFRHQXL \d_comb_reg[2][0][9] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [9]), .Q (\d_comb[2][0] [9]));
  DFFRHQXL \d_comb_reg[2][0][10] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [10]), .Q (\d_comb[2][0] [10]));
  DFFRHQXL \d_comb_reg[2][0][11] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [11]), .Q (\d_comb[2][0] [11]));
  DFFRHQXL \d_comb_reg[2][0][12] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [12]), .Q (\d_comb[2][0] [12]));
  DFFRHQXL \d_comb_reg[2][0][13] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [13]), .Q (\d_comb[2][0] [13]));
  DFFRHQXL \d_comb_reg[2][0][14] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [14]), .Q (\d_comb[2][0] [14]));
  DFFRHQXL \d_comb_reg[2][0][15] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [15]), .Q (\d_comb[2][0] [15]));
  DFFRHQXL \d_comb_reg[2][0][16] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [16]), .Q (\d_comb[2][0] [16]));
  DFFRHQXL \d_comb_reg[2][0][17] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [17]), .Q (\d_comb[2][0] [17]));
  DFFRHQXL \d_comb_reg[2][0][18] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [18]), .Q (\d_comb[2][0] [18]));
  DFFRHQXL \d_comb_reg[2][0][19] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[1] [19]), .Q (\d_comb[2][0] [19]));
  DFFRHQXL \d_comb_reg[3][0][0] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [0]), .Q (\d_comb[3][0] [0]));
  DFFRHQXL \d_comb_reg[3][0][1] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [1]), .Q (\d_comb[3][0] [1]));
  DFFRHQXL \d_comb_reg[3][0][2] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [2]), .Q (\d_comb[3][0] [2]));
  DFFRHQXL \d_comb_reg[3][0][3] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [3]), .Q (\d_comb[3][0] [3]));
  DFFRHQXL \d_comb_reg[3][0][4] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [4]), .Q (\d_comb[3][0] [4]));
  DFFRHQXL \d_comb_reg[3][0][5] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [5]), .Q (\d_comb[3][0] [5]));
  DFFRHQXL \d_comb_reg[3][0][6] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [6]), .Q (\d_comb[3][0] [6]));
  DFFRHQXL \d_comb_reg[3][0][7] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [7]), .Q (\d_comb[3][0] [7]));
  DFFRHQXL \d_comb_reg[3][0][8] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [8]), .Q (\d_comb[3][0] [8]));
  DFFRHQXL \d_comb_reg[3][0][9] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [9]), .Q (\d_comb[3][0] [9]));
  DFFRHQXL \d_comb_reg[3][0][10] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [10]), .Q (\d_comb[3][0] [10]));
  DFFRHQXL \d_comb_reg[3][0][11] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [11]), .Q (\d_comb[3][0] [11]));
  DFFRHQXL \d_comb_reg[3][0][12] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [12]), .Q (\d_comb[3][0] [12]));
  DFFRHQXL \d_comb_reg[3][0][13] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [13]), .Q (\d_comb[3][0] [13]));
  DFFRHQXL \d_comb_reg[3][0][14] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [14]), .Q (\d_comb[3][0] [14]));
  DFFRHQXL \d_comb_reg[3][0][15] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [15]), .Q (\d_comb[3][0] [15]));
  DFFRHQXL \d_comb_reg[3][0][16] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [16]), .Q (\d_comb[3][0] [16]));
  DFFRHQXL \d_comb_reg[3][0][17] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [17]), .Q (\d_comb[3][0] [17]));
  DFFRHQXL \d_comb_reg[3][0][18] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [18]), .Q (\d_comb[3][0] [18]));
  DFFRHQXL \d_comb_reg[3][0][19] (.RN (n_0), .CK (rc_gclk), .D
       (\comb[2] [19]), .Q (\d_comb[3][0] [19]));
  DFFRHQXL \d_comb_reg[3][1][0] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [0]), .Q (\d_comb[3][1] [0]));
  DFFRHQXL \d_comb_reg[3][1][1] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [1]), .Q (\d_comb[3][1] [1]));
  DFFRXL \d_comb_reg[3][1][2] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [2]), .Q (UNCONNECTED2), .QN (\d_comb[3][1] [2]));
  DFFRXL \d_comb_reg[3][1][3] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [3]), .Q (UNCONNECTED3), .QN (\d_comb[3][1] [3]));
  DFFRHQXL \d_comb_reg[3][1][4] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [4]), .Q (\d_comb[3][1] [4]));
  DFFRXL \d_comb_reg[3][1][5] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [5]), .Q (UNCONNECTED4), .QN (\d_comb[3][1] [5]));
  DFFRHQXL \d_comb_reg[3][1][6] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [6]), .Q (\d_comb[3][1] [6]));
  DFFRXL \d_comb_reg[3][1][7] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [7]), .Q (UNCONNECTED5), .QN (\d_comb[3][1] [7]));
  DFFRXL \d_comb_reg[3][1][8] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [8]), .Q (UNCONNECTED6), .QN (\d_comb[3][1] [8]));
  DFFRHQXL \d_comb_reg[3][1][9] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [9]), .Q (\d_comb[3][1] [9]));
  DFFRHQXL \d_comb_reg[3][1][10] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [10]), .Q (\d_comb[3][1] [10]));
  DFFRXL \d_comb_reg[3][1][11] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [11]), .Q (UNCONNECTED7), .QN (\d_comb[3][1]
       [11]));
  DFFRHQXL \d_comb_reg[3][1][12] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [12]), .Q (\d_comb[3][1] [12]));
  DFFRXL \d_comb_reg[3][1][13] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [13]), .Q (UNCONNECTED8), .QN (\d_comb[3][1]
       [13]));
  DFFRXL \d_comb_reg[3][1][14] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [14]), .Q (UNCONNECTED9), .QN (\d_comb[3][1]
       [14]));
  DFFRHQXL \d_comb_reg[3][1][15] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [15]), .Q (\d_comb[3][1] [15]));
  DFFRXL \d_comb_reg[3][1][16] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [16]), .Q (UNCONNECTED10), .QN (\d_comb[3][1]
       [16]));
  DFFRXL \d_comb_reg[3][1][17] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [17]), .Q (UNCONNECTED11), .QN (\d_comb[3][1]
       [17]));
  DFFRXL \d_comb_reg[3][1][18] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [18]), .Q (UNCONNECTED12), .QN (\d_comb[3][1]
       [18]));
  DFFRHQXL \d_comb_reg[3][1][19] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[3][0] [19]), .Q (\d_comb[3][1] [19]));
  XNOR3X2 g2305__6783(.A (n_29), .B (n_14), .C (n_50), .Y (d_out[3]));
  ADDFX2 g2306__3680(.A (n_30), .B (n_25), .CI (n_49), .S (d_out[2]),
       .CO (n_50));
  ADDFX2 g2307__1617(.A (n_26), .B (n_27), .CI (n_48), .S (d_out[1]),
       .CO (n_49));
  ADDFX2 g2308__2802(.A (n_28), .B (\comb[2] [15]), .CI (n_47), .S
       (d_out[0]), .CO (n_48));
  OAI221XL g2309__1705(.A0 (n_18), .A1 (n_33), .B0 (\comb[2] [15]), .B1
       (\d_comb[3][1] [15]), .C0 (n_46), .Y (n_47));
  AOI31XL g2310__5122(.A0 (n_11), .A1 (\comb[2] [14]), .A2
       (\d_comb[3][1] [14]), .B0 (n_45), .Y (n_46));
  NOR4BXL g2311__8246(.AN (n_10), .B (n_44), .C (n_18), .D (n_8), .Y
       (n_45));
  AOI221XL g2312__7098(.A0 (n_20), .A1 (\comb[2] [10]), .B0
       (\comb[2] [9]), .B1 (n_42), .C0 (n_43), .Y (n_44));
  OAI2BB2XL g2313__6131(.A0N (\d_comb[3][1] [11]), .A1N (\comb[2]
       [11]), .B0 (n_41), .B1 (\d_comb[3][1] [9]), .Y (n_43));
  OAI21XL g2314__1881(.A0 (n_15), .A1 (\d_comb[3][1] [9]), .B0 (n_41),
       .Y (n_42));
  AOI33XL g2315__5115(.A0 (n_40), .A1 (n_16), .A2 (\comb[2] [8]), .B0
       (n_39), .B1 (\d_comb[3][1] [8]), .B2 (n_16), .Y (n_41));
  OR2X1 g2316__7482(.A (n_39), .B (\d_comb[3][1] [8]), .Y (n_40));
  OAI2BB1XL g2317__4733(.A0N (\comb[2] [5]), .A1N (n_37), .B0 (n_38),
       .Y (n_39));
  AOI222XL g2318__6161(.A0 (n_36), .A1 (\d_comb[3][1] [5]), .B0
       (\comb[2] [7]), .B1 (\d_comb[3][1] [7]), .C0 (n_21), .C1
       (\comb[2] [6]), .Y (n_38));
  OR2X1 g2319__9315(.A (n_36), .B (n_24), .Y (n_37));
  OAI2BB2XL g2320__9945(.A0N (n_35), .A1N (n_32), .B0 (n_23), .B1
       (\d_comb[3][1] [4]), .Y (n_36));
  OAI2BB2XL g2321__2883(.A0N (\d_comb[3][1] [3]), .A1N (\comb[2] [3]),
       .B0 (n_6), .B1 (n_34), .Y (n_35));
  AOI22XL g2322__2346(.A0 (n_7), .A1 (n_31), .B0 (\d_comb[3][1] [2]),
       .B1 (\comb[2] [2]), .Y (n_34));
  AOI22XL g2323__1666(.A0 (n_19), .A1 (\comb[2] [12]), .B0
       (\d_comb[3][1] [13]), .B1 (\comb[2] [13]), .Y (n_33));
  OAI21XL g2324__7410(.A0 (n_17), .A1 (\d_comb[3][1] [4]), .B0 (n_23),
       .Y (n_32));
  OAI21XL g2325__6417(.A0 (n_9), .A1 (\d_comb[3][1] [1]), .B0 (n_22),
       .Y (n_31));
  ADDHXL g2326__5477(.A (\d_comb[3][1] [18]), .B (\comb[2] [18]), .S
       (n_30), .CO (n_29));
  ADDHXL g2327__2398(.A (\d_comb[3][1] [16]), .B (\comb[2] [16]), .S
       (n_28), .CO (n_27));
  ADDHXL g2328__5107(.A (\d_comb[3][1] [17]), .B (\comb[2] [17]), .S
       (n_26), .CO (n_25));
  NOR2BXL g2329__6260(.AN (\d_comb[3][1] [5]), .B (n_17), .Y (n_24));
  OAI2BB1XL g2330__4319(.A0N (\d_comb[3][1] [1]), .A1N (n_9), .B0
       (\comb[2] [1]), .Y (n_22));
  NAND2BXL g2331__8428(.AN (n_17), .B (\comb[2] [4]), .Y (n_23));
  NOR2XL g2332__5526(.A (n_12), .B (\d_comb[3][1] [6]), .Y (n_21));
  NOR2XL g2333__6783(.A (n_13), .B (\d_comb[3][1] [10]), .Y (n_20));
  NOR2XL g2334__3680(.A (n_8), .B (\d_comb[3][1] [12]), .Y (n_19));
  INVX1 g2335(.A (n_16), .Y (n_15));
  OAI21XL g2336__1617(.A0 (\comb[2] [14]), .A1 (\d_comb[3][1] [14]),
       .B0 (n_11), .Y (n_18));
  XOR2XL g2337__2802(.A (\d_comb[3][1] [19]), .B (\comb[2] [19]), .Y
       (n_14));
  OR2X1 g2338__1705(.A (n_12), .B (n_5), .Y (n_17));
  AOI21XL g2339__5122(.A0 (n_3), .A1 (\d_comb[3][1] [10]), .B0 (n_13),
       .Y (n_16));
  NAND2BXL g2340__8246(.AN (\comb[2] [12]), .B (\d_comb[3][1] [12]), .Y
       (n_10));
  NOR2XL g2341__7098(.A (\comb[2] [11]), .B (\d_comb[3][1] [11]), .Y
       (n_13));
  NOR2XL g2342__6131(.A (\comb[2] [7]), .B (\d_comb[3][1] [7]), .Y
       (n_12));
  NAND2XL g2343__1881(.A (\d_comb[3][1] [15]), .B (\comb[2] [15]), .Y
       (n_11));
  OR2X1 g2344__5115(.A (\comb[2] [2]), .B (\d_comb[3][1] [2]), .Y
       (n_7));
  NOR2XL g2345__7482(.A (\comb[2] [3]), .B (\d_comb[3][1] [3]), .Y
       (n_6));
  NOR2BXL g2346__4733(.AN (\d_comb[3][1] [6]), .B (\comb[2] [6]), .Y
       (n_5));
  NOR2BXL g2347__6161(.AN (\d_comb[3][1] [0]), .B (\comb[2] [0]), .Y
       (n_9));
  NOR2XL g2348__9315(.A (\comb[2] [13]), .B (\d_comb[3][1] [13]), .Y
       (n_8));
  AND2X1 g2429__9945(.A (ce_1), .B (ce_2), .Y (n_60));
  INVXL g2430(.A (rst), .Y (n_0));
  INVX1 g2431(.A (\comb[2] [10]), .Y (n_3));
  DFFRHQX1 \d_comb_reg[0][1][0] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [0]), .Q (\d_comb[0][1] [0]));
  DFFRHQX1 \d_comb_reg[0][1][19] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [19]), .Q (\d_comb[0][1] [19]));
  DFFRHQXL \d_comb_reg[0][0][2] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[2]), .Q (\d_comb[0][0] [2]));
  DFFRHQXL \d_comb_reg[0][0][3] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[3]), .Q (\d_comb[0][0] [3]));
  DFFRHQXL \d_comb_reg[0][0][4] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[4]), .Q (\d_comb[0][0] [4]));
  DFFRHQXL \d_comb_reg[0][0][5] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[5]), .Q (\d_comb[0][0] [5]));
  DFFRHQXL \d_comb_reg[0][0][6] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[6]), .Q (\d_comb[0][0] [6]));
  DFFRHQXL \d_comb_reg[0][0][7] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[7]), .Q (\d_comb[0][0] [7]));
  DFFRHQXL \d_comb_reg[0][0][8] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[8]), .Q (\d_comb[0][0] [8]));
  DFFRHQXL \d_comb_reg[0][0][9] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[9]), .Q (\d_comb[0][0] [9]));
  DFFRHQXL \d_comb_reg[0][0][10] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[10]), .Q (\d_comb[0][0] [10]));
  DFFRHQXL \d_comb_reg[0][0][11] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[11]), .Q (\d_comb[0][0] [11]));
  DFFRHQXL \d_comb_reg[0][0][12] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[12]), .Q (\d_comb[0][0] [12]));
  DFFRHQXL \d_comb_reg[0][0][13] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[13]), .Q (\d_comb[0][0] [13]));
  DFFRHQXL \d_comb_reg[0][0][14] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[14]), .Q (\d_comb[0][0] [14]));
  DFFRHQXL \d_comb_reg[0][0][0] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[0]), .Q (\d_comb[0][0] [0]));
  DFFRHQXL \d_comb_reg[0][0][17] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[17]), .Q (\d_comb[0][0] [17]));
  DFFRHQXL \d_comb_reg[0][0][18] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[18]), .Q (\d_comb[0][0] [18]));
  DFFRHQXL \d_comb_reg[0][0][1] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[1]), .Q (\d_comb[0][0] [1]));
  DFFRHQXL \d_comb_reg[0][0][19] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[19]), .Q (\d_comb[0][0] [19]));
  DFFRHQXL \d_comb_reg[0][0][15] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[15]), .Q (\d_comb[0][0] [15]));
  DFFRHQXL \d_comb_reg[0][0][16] (.RN (n_0), .CK (rc_gclk), .D
       (d_tmp[16]), .Q (\d_comb[0][0] [16]));
  DFFRHQX1 \d_tmp_reg[18] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [18]), .Q (d_tmp[18]));
  DFFRHQX1 \d_tmp_reg[14] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [14]), .Q (d_tmp[14]));
  DFFRHQX1 \d_tmp_reg[6] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [6]), .Q (d_tmp[6]));
  DFFRHQX1 \d_tmp_reg[1] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [1]), .Q (d_tmp[1]));
  DFFRHQX1 \d_tmp_reg[2] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [2]), .Q (d_tmp[2]));
  DFFRHQX1 \d_tmp_reg[3] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [3]), .Q (d_tmp[3]));
  DFFRHQX1 \d_tmp_reg[4] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [4]), .Q (d_tmp[4]));
  DFFRHQX1 \d_tmp_reg[5] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [5]), .Q (d_tmp[5]));
  DFFRHQX1 \d_tmp_reg[7] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [7]), .Q (d_tmp[7]));
  DFFRHQX1 \d_tmp_reg[8] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [8]), .Q (d_tmp[8]));
  DFFRHQX1 \d_tmp_reg[9] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [9]), .Q (d_tmp[9]));
  DFFRHQX1 \d_tmp_reg[10] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [10]), .Q (d_tmp[10]));
  DFFRHQX1 \d_tmp_reg[11] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [11]), .Q (d_tmp[11]));
  DFFRHQX1 \d_tmp_reg[12] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [12]), .Q (d_tmp[12]));
  DFFRHQX1 \d_tmp_reg[13] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [13]), .Q (d_tmp[13]));
  DFFRHQX1 \d_tmp_reg[15] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [15]), .Q (d_tmp[15]));
  DFFRHQX1 \d_tmp_reg[16] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [16]), .Q (d_tmp[16]));
  DFFRHQX1 \d_tmp_reg[17] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [17]), .Q (d_tmp[17]));
  DFFRHQX1 \d_tmp_reg[19] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [19]), .Q (d_tmp[19]));
  DFFRHQX1 \integrator_reg[0][17] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_124), .Q (\integrator[0] [17]));
  DFFRHQX1 \integrator_reg[0][1] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_140), .Q (\integrator[0] [1]));
  DFFRHQX1 \integrator_reg[0][2] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_139), .Q (\integrator[0] [2]));
  DFFRHQX1 \integrator_reg[0][3] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_138), .Q (\integrator[0] [3]));
  DFFRHQX1 \integrator_reg[0][4] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_137), .Q (\integrator[0] [4]));
  DFFRHQX1 \integrator_reg[3][15] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_66), .Q (\integrator[3] [15]));
  DFFRHQX1 \integrator_reg[0][5] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_136), .Q (\integrator[0] [5]));
  DFFRHQX1 \integrator_reg[0][6] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_135), .Q (\integrator[0] [6]));
  DFFRHQX1 \integrator_reg[0][7] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_134), .Q (\integrator[0] [7]));
  DFFRHQX1 \integrator_reg[3][11] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_70), .Q (\integrator[3] [11]));
  DFFRHQX1 \integrator_reg[0][8] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_133), .Q (\integrator[0] [8]));
  DFFRHQX1 \integrator_reg[0][9] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_132), .Q (\integrator[0] [9]));
  DFFRHQX1 \integrator_reg[0][10] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_131), .Q (\integrator[0] [10]));
  DFFRHQX1 \integrator_reg[3][7] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_74), .Q (\integrator[3] [7]));
  DFFRHQX1 \integrator_reg[0][11] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_130), .Q (\integrator[0] [11]));
  DFFRHQX1 \integrator_reg[0][12] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_129), .Q (\integrator[0] [12]));
  DFFRHQX1 \integrator_reg[0][13] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_128), .Q (\integrator[0] [13]));
  DFFRHQX1 \integrator_reg[0][14] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_127), .Q (\integrator[0] [14]));
  DFFRHQX1 \integrator_reg[0][15] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_126), .Q (\integrator[0] [15]));
  DFFRHQX1 \integrator_reg[0][16] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_125), .Q (\integrator[0] [16]));
  DFFRHQX1 \integrator_reg[0][0] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_141), .Q (\integrator[0] [0]));
  DFFRHQX1 \integrator_reg[2][19] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_82), .Q (\integrator[2] [19]));
  DFFRHQX1 \integrator_reg[0][18] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_123), .Q (\integrator[0] [18]));
  DFFRHQX1 \integrator_reg[0][19] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_122), .Q (\integrator[0] [19]));
  DFFRHQX1 \integrator_reg[1][0] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_121), .Q (\integrator[1] [0]));
  DFFRHQX1 \integrator_reg[2][15] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_86), .Q (\integrator[2] [15]));
  DFFRHQX1 \integrator_reg[1][1] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_120), .Q (\integrator[1] [1]));
  DFFRHQX1 \integrator_reg[1][2] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_119), .Q (\integrator[1] [2]));
  DFFRHQX1 \integrator_reg[1][3] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_118), .Q (\integrator[1] [3]));
  DFFRHQX1 \integrator_reg[2][11] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_90), .Q (\integrator[2] [11]));
  DFFRHQX1 \integrator_reg[1][4] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_117), .Q (\integrator[1] [4]));
  DFFRHQX1 \integrator_reg[1][5] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_116), .Q (\integrator[1] [5]));
  DFFRHQX1 \integrator_reg[1][6] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_115), .Q (\integrator[1] [6]));
  DFFRHQX1 \integrator_reg[1][7] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_114), .Q (\integrator[1] [7]));
  DFFRHQX1 \integrator_reg[1][8] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_113), .Q (\integrator[1] [8]));
  DFFRHQX1 \integrator_reg[1][9] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_112), .Q (\integrator[1] [9]));
  DFFRHQX1 \integrator_reg[1][10] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_111), .Q (\integrator[1] [10]));
  DFFRHQX1 \integrator_reg[2][3] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_98), .Q (\integrator[2] [3]));
  DFFRHQX1 \integrator_reg[1][11] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_110), .Q (\integrator[1] [11]));
  DFFRHQX1 \integrator_reg[1][12] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_109), .Q (\integrator[1] [12]));
  DFFRHQX1 \integrator_reg[2][16] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_85), .Q (\integrator[2] [16]));
  DFFRHQX1 \integrator_reg[1][14] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_107), .Q (\integrator[1] [14]));
  DFFRHQX1 \integrator_reg[1][15] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_106), .Q (\integrator[1] [15]));
  DFFRHQX1 \integrator_reg[1][16] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_105), .Q (\integrator[1] [16]));
  DFFRHQX1 \integrator_reg[1][17] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_104), .Q (\integrator[1] [17]));
  DFFRHQX1 \integrator_reg[1][18] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_103), .Q (\integrator[1] [18]));
  DFFRHQX1 \integrator_reg[1][19] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_102), .Q (\integrator[1] [19]));
  DFFRHQX1 \integrator_reg[2][0] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_101), .Q (\integrator[2] [0]));
  DFFRHQX1 \integrator_reg[2][1] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_100), .Q (\integrator[2] [1]));
  DFFRHQX1 \integrator_reg[2][2] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_99), .Q (\integrator[2] [2]));
  DFFRHQX1 \integrator_reg[2][4] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_97), .Q (\integrator[2] [4]));
  DFFRHQX1 \integrator_reg[2][5] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_96), .Q (\integrator[2] [5]));
  DFFRHQX1 \integrator_reg[2][6] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_95), .Q (\integrator[2] [6]));
  DFFRHQX1 \integrator_reg[2][7] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_94), .Q (\integrator[2] [7]));
  DFFRHQX1 \integrator_reg[2][8] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_93), .Q (\integrator[2] [8]));
  DFFRHQX1 \integrator_reg[2][9] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_92), .Q (\integrator[2] [9]));
  DFFRHQX1 \integrator_reg[2][10] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_91), .Q (\integrator[2] [10]));
  DFFRHQX1 \integrator_reg[2][12] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_89), .Q (\integrator[2] [12]));
  DFFRHQX1 \integrator_reg[2][13] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_88), .Q (\integrator[2] [13]));
  DFFRHQX1 \integrator_reg[2][14] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_87), .Q (\integrator[2] [14]));
  DFFRHQX1 \integrator_reg[1][13] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_108), .Q (\integrator[1] [13]));
  DFFRHQX1 \integrator_reg[2][17] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_84), .Q (\integrator[2] [17]));
  DFFRHQX1 \integrator_reg[2][18] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_83), .Q (\integrator[2] [18]));
  DFFRHQX1 \integrator_reg[3][0] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_81), .Q (\integrator[3] [0]));
  DFFRHQX1 \integrator_reg[3][1] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_80), .Q (\integrator[3] [1]));
  DFFRHQX1 \integrator_reg[3][2] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_79), .Q (\integrator[3] [2]));
  DFFRHQX1 \integrator_reg[3][3] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_78), .Q (\integrator[3] [3]));
  DFFRHQX1 \integrator_reg[3][4] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_77), .Q (\integrator[3] [4]));
  DFFRHQX1 \integrator_reg[3][5] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_76), .Q (\integrator[3] [5]));
  DFFRHQX1 \integrator_reg[3][6] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_75), .Q (\integrator[3] [6]));
  DFFRHQX1 \integrator_reg[3][8] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_73), .Q (\integrator[3] [8]));
  DFFRHQX1 \integrator_reg[3][9] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_72), .Q (\integrator[3] [9]));
  DFFRHQX1 \integrator_reg[3][10] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_71), .Q (\integrator[3] [10]));
  DFFRHQX1 \integrator_reg[3][12] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_69), .Q (\integrator[3] [12]));
  DFFRHQX1 \integrator_reg[3][13] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_68), .Q (\integrator[3] [13]));
  DFFRHQX1 \integrator_reg[3][14] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_67), .Q (\integrator[3] [14]));
  DFFRHQX1 \integrator_reg[3][16] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_65), .Q (\integrator[3] [16]));
  DFFRHQX1 \integrator_reg[3][17] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_64), .Q (\integrator[3] [17]));
  DFFRHQX1 \integrator_reg[3][18] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_63), .Q (\integrator[3] [18]));
  DFFRHQX1 \integrator_reg[3][19] (.RN (n_0), .CK (rc_gclk_1227), .D
       (n_62), .Q (\integrator[3] [19]));
  DFFRHQX1 \d_comb_reg[1][1][0] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [0]), .Q (\d_comb[1][1] [0]));
  DFFRHQX1 \d_comb_reg[2][1][19] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [19]), .Q (\d_comb[2][1] [19]));
  DFFRHQX1 \d_comb_reg[1][1][19] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [19]), .Q (\d_comb[1][1] [19]));
  DFFRHQX1 \d_comb_reg[2][1][0] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [0]), .Q (\d_comb[2][1] [0]));
  XNOR3X2 sub_75_30_I2_g1316__2883(.A (\d_comb[2][1] [19]), .B
       (\comb[1] [19]), .C (sub_75_30_I2_n_655), .Y (\comb[2] [19]));
  ADDFX2 sub_75_30_I2_g1317__2346(.A (\comb[1] [18]), .B
       (sub_75_30_I2_n_709), .CI (sub_75_30_I2_n_657), .S (\comb[2]
       [18]), .CO (sub_75_30_I2_n_655));
  ADDFX2 sub_75_30_I2_g1318__1666(.A (\comb[1] [17]), .B
       (sub_75_30_I2_n_700), .CI (sub_75_30_I2_n_659), .S (\comb[2]
       [17]), .CO (sub_75_30_I2_n_657));
  ADDFX2 sub_75_30_I2_g1319__7410(.A (\comb[1] [16]), .B
       (sub_75_30_I2_n_706), .CI (sub_75_30_I2_n_661), .S (\comb[2]
       [16]), .CO (sub_75_30_I2_n_659));
  ADDFX2 sub_75_30_I2_g1320__6417(.A (\comb[1] [15]), .B
       (sub_75_30_I2_n_710), .CI (sub_75_30_I2_n_663), .S (\comb[2]
       [15]), .CO (sub_75_30_I2_n_661));
  ADDFX2 sub_75_30_I2_g1321__5477(.A (\comb[1] [14]), .B
       (sub_75_30_I2_n_696), .CI (sub_75_30_I2_n_665), .S (\comb[2]
       [14]), .CO (sub_75_30_I2_n_663));
  ADDFX2 sub_75_30_I2_g1322__2398(.A (\comb[1] [13]), .B
       (sub_75_30_I2_n_699), .CI (sub_75_30_I2_n_667), .S (\comb[2]
       [13]), .CO (sub_75_30_I2_n_665));
  ADDFX2 sub_75_30_I2_g1323__5107(.A (\comb[1] [12]), .B
       (sub_75_30_I2_n_703), .CI (sub_75_30_I2_n_669), .S (\comb[2]
       [12]), .CO (sub_75_30_I2_n_667));
  ADDFX2 sub_75_30_I2_g1324__6260(.A (\comb[1] [11]), .B
       (sub_75_30_I2_n_702), .CI (sub_75_30_I2_n_671), .S (\comb[2]
       [11]), .CO (sub_75_30_I2_n_669));
  ADDFX2 sub_75_30_I2_g1325__4319(.A (\comb[1] [10]), .B
       (sub_75_30_I2_n_711), .CI (sub_75_30_I2_n_673), .S (\comb[2]
       [10]), .CO (sub_75_30_I2_n_671));
  ADDFX2 sub_75_30_I2_g1326__8428(.A (\comb[1] [9]), .B
       (sub_75_30_I2_n_701), .CI (sub_75_30_I2_n_675), .S (\comb[2]
       [9]), .CO (sub_75_30_I2_n_673));
  ADDFX2 sub_75_30_I2_g1327__5526(.A (\comb[1] [8]), .B
       (sub_75_30_I2_n_708), .CI (sub_75_30_I2_n_677), .S (\comb[2]
       [8]), .CO (sub_75_30_I2_n_675));
  ADDFX2 sub_75_30_I2_g1328__6783(.A (\comb[1] [7]), .B
       (sub_75_30_I2_n_698), .CI (sub_75_30_I2_n_679), .S (\comb[2]
       [7]), .CO (sub_75_30_I2_n_677));
  ADDFX2 sub_75_30_I2_g1329__3680(.A (\comb[1] [6]), .B
       (sub_75_30_I2_n_704), .CI (sub_75_30_I2_n_681), .S (\comb[2]
       [6]), .CO (sub_75_30_I2_n_679));
  ADDFX2 sub_75_30_I2_g1330__1617(.A (\comb[1] [5]), .B
       (sub_75_30_I2_n_714), .CI (sub_75_30_I2_n_683), .S (\comb[2]
       [5]), .CO (sub_75_30_I2_n_681));
  ADDFX2 sub_75_30_I2_g1331__2802(.A (\comb[1] [4]), .B
       (sub_75_30_I2_n_713), .CI (sub_75_30_I2_n_685), .S (\comb[2]
       [4]), .CO (sub_75_30_I2_n_683));
  ADDFX2 sub_75_30_I2_g1332__1705(.A (\comb[1] [3]), .B
       (sub_75_30_I2_n_705), .CI (sub_75_30_I2_n_687), .S (\comb[2]
       [3]), .CO (sub_75_30_I2_n_685));
  ADDFX2 sub_75_30_I2_g1333__5122(.A (\comb[1] [2]), .B
       (sub_75_30_I2_n_712), .CI (sub_75_30_I2_n_689), .S (\comb[2]
       [2]), .CO (sub_75_30_I2_n_687));
  ADDFX2 sub_75_30_I2_g1334__8246(.A (sub_75_30_I2_n_692), .B
       (sub_75_30_I2_n_695), .CI (\comb[1] [1]), .S (\comb[2] [1]), .CO
       (sub_75_30_I2_n_689));
  OAI21XL sub_75_30_I2_g1335__7098(.A0 (sub_75_30_I2_n_707), .A1
       (\d_comb[2][1] [0]), .B0 (sub_75_30_I2_n_692), .Y (\comb[2]
       [0]));
  NAND2X1 sub_75_30_I2_g1336__6131(.A (sub_75_30_I2_n_707), .B
       (\d_comb[2][1] [0]), .Y (sub_75_30_I2_n_692));
  INVX1 sub_75_30_I2_g1348(.A (\comb[1] [0]), .Y (sub_75_30_I2_n_707));
  XNOR3X2 sub_75_30_I1_g1316__1881(.A (\d_comb[1][1] [19]), .B
       (\comb[0] [19]), .C (sub_75_30_I1_n_655), .Y (\comb[1] [19]));
  ADDFX2 sub_75_30_I1_g1317__5115(.A (\comb[0] [18]), .B
       (sub_75_30_I1_n_709), .CI (sub_75_30_I1_n_657), .S (\comb[1]
       [18]), .CO (sub_75_30_I1_n_655));
  ADDFX2 sub_75_30_I1_g1318__7482(.A (\comb[0] [17]), .B
       (sub_75_30_I1_n_700), .CI (sub_75_30_I1_n_659), .S (\comb[1]
       [17]), .CO (sub_75_30_I1_n_657));
  ADDFX2 sub_75_30_I1_g1319__4733(.A (\comb[0] [16]), .B
       (sub_75_30_I1_n_706), .CI (sub_75_30_I1_n_661), .S (\comb[1]
       [16]), .CO (sub_75_30_I1_n_659));
  ADDFX2 sub_75_30_I1_g1320__6161(.A (\comb[0] [15]), .B
       (sub_75_30_I1_n_710), .CI (sub_75_30_I1_n_663), .S (\comb[1]
       [15]), .CO (sub_75_30_I1_n_661));
  ADDFX2 sub_75_30_I1_g1321__9315(.A (\comb[0] [14]), .B
       (sub_75_30_I1_n_696), .CI (sub_75_30_I1_n_665), .S (\comb[1]
       [14]), .CO (sub_75_30_I1_n_663));
  ADDFX2 sub_75_30_I1_g1322__9945(.A (\comb[0] [13]), .B
       (sub_75_30_I1_n_699), .CI (sub_75_30_I1_n_667), .S (\comb[1]
       [13]), .CO (sub_75_30_I1_n_665));
  ADDFX2 sub_75_30_I1_g1323__2883(.A (\comb[0] [12]), .B
       (sub_75_30_I1_n_703), .CI (sub_75_30_I1_n_669), .S (\comb[1]
       [12]), .CO (sub_75_30_I1_n_667));
  ADDFX2 sub_75_30_I1_g1324__2346(.A (\comb[0] [11]), .B
       (sub_75_30_I1_n_702), .CI (sub_75_30_I1_n_671), .S (\comb[1]
       [11]), .CO (sub_75_30_I1_n_669));
  ADDFX2 sub_75_30_I1_g1325__1666(.A (\comb[0] [10]), .B
       (sub_75_30_I1_n_711), .CI (sub_75_30_I1_n_673), .S (\comb[1]
       [10]), .CO (sub_75_30_I1_n_671));
  ADDFX2 sub_75_30_I1_g1326__7410(.A (\comb[0] [9]), .B
       (sub_75_30_I1_n_701), .CI (sub_75_30_I1_n_675), .S (\comb[1]
       [9]), .CO (sub_75_30_I1_n_673));
  ADDFX1 sub_75_30_I1_g1327__6417(.A (\comb[0] [8]), .B
       (sub_75_30_I1_n_708), .CI (sub_75_30_I1_n_677), .S (\comb[1]
       [8]), .CO (sub_75_30_I1_n_675));
  ADDFX2 sub_75_30_I1_g1328__5477(.A (\comb[0] [7]), .B
       (sub_75_30_I1_n_698), .CI (sub_75_30_I1_n_679), .S (\comb[1]
       [7]), .CO (sub_75_30_I1_n_677));
  ADDFX2 sub_75_30_I1_g1329__2398(.A (\comb[0] [6]), .B
       (sub_75_30_I1_n_704), .CI (sub_75_30_I1_n_681), .S (\comb[1]
       [6]), .CO (sub_75_30_I1_n_679));
  ADDFX2 sub_75_30_I1_g1330__5107(.A (\comb[0] [5]), .B
       (sub_75_30_I1_n_714), .CI (sub_75_30_I1_n_683), .S (\comb[1]
       [5]), .CO (sub_75_30_I1_n_681));
  ADDFX2 sub_75_30_I1_g1331__6260(.A (\comb[0] [4]), .B
       (sub_75_30_I1_n_713), .CI (sub_75_30_I1_n_685), .S (\comb[1]
       [4]), .CO (sub_75_30_I1_n_683));
  ADDFX2 sub_75_30_I1_g1332__4319(.A (\comb[0] [3]), .B
       (sub_75_30_I1_n_705), .CI (sub_75_30_I1_n_687), .S (\comb[1]
       [3]), .CO (sub_75_30_I1_n_685));
  ADDFX2 sub_75_30_I1_g1333__8428(.A (\comb[0] [2]), .B
       (sub_75_30_I1_n_712), .CI (sub_75_30_I1_n_689), .S (\comb[1]
       [2]), .CO (sub_75_30_I1_n_687));
  ADDFX2 sub_75_30_I1_g1334__5526(.A (\comb[0] [1]), .B
       (sub_75_30_I1_n_695), .CI (sub_75_30_I1_n_692), .S (\comb[1]
       [1]), .CO (sub_75_30_I1_n_689));
  OAI21XL sub_75_30_I1_g1335__6783(.A0 (sub_75_30_I1_n_707), .A1
       (\d_comb[1][1] [0]), .B0 (sub_75_30_I1_n_692), .Y (\comb[1]
       [0]));
  NAND2X1 sub_75_30_I1_g1336__3680(.A (sub_75_30_I1_n_707), .B
       (\d_comb[1][1] [0]), .Y (sub_75_30_I1_n_692));
  INVX1 sub_75_30_I1_g1348(.A (\comb[0] [0]), .Y (sub_75_30_I1_n_707));
  XOR3X2 ADD_TC_OP_g464__1617(.A (d_in[3]), .B (\integrator[0] [19]),
       .C (ADD_TC_OP_n_36), .Y (n_122));
  ADDFX2 ADD_TC_OP_g465__2802(.A (\integrator[0] [18]), .B (d_in[3]),
       .CI (ADD_TC_OP_n_34), .S (n_123), .CO (ADD_TC_OP_n_36));
  ADDFX2 ADD_TC_OP_g466__1705(.A (\integrator[0] [17]), .B (d_in[3]),
       .CI (ADD_TC_OP_n_32), .S (n_124), .CO (ADD_TC_OP_n_34));
  ADDFX2 ADD_TC_OP_g467__5122(.A (\integrator[0] [16]), .B (d_in[3]),
       .CI (ADD_TC_OP_n_30), .S (n_125), .CO (ADD_TC_OP_n_32));
  ADDFX2 ADD_TC_OP_g468__8246(.A (\integrator[0] [15]), .B (d_in[3]),
       .CI (ADD_TC_OP_n_28), .S (n_126), .CO (ADD_TC_OP_n_30));
  ADDFX2 ADD_TC_OP_g469__7098(.A (\integrator[0] [14]), .B (d_in[3]),
       .CI (ADD_TC_OP_n_26), .S (n_127), .CO (ADD_TC_OP_n_28));
  ADDFX2 ADD_TC_OP_g470__6131(.A (\integrator[0] [13]), .B (d_in[3]),
       .CI (ADD_TC_OP_n_24), .S (n_128), .CO (ADD_TC_OP_n_26));
  ADDFX2 ADD_TC_OP_g471__1881(.A (\integrator[0] [12]), .B (d_in[3]),
       .CI (ADD_TC_OP_n_22), .S (n_129), .CO (ADD_TC_OP_n_24));
  ADDFX2 ADD_TC_OP_g472__5115(.A (ADD_TC_OP_n_20), .B (d_in[3]), .CI
       (\integrator[0] [11]), .S (n_130), .CO (ADD_TC_OP_n_22));
  ADDFX2 ADD_TC_OP_g473__7482(.A (ADD_TC_OP_n_18), .B (d_in[3]), .CI
       (\integrator[0] [10]), .S (n_131), .CO (ADD_TC_OP_n_20));
  ADDFX2 ADD_TC_OP_g474__4733(.A (ADD_TC_OP_n_16), .B (d_in[3]), .CI
       (\integrator[0] [9]), .S (n_132), .CO (ADD_TC_OP_n_18));
  ADDFX2 ADD_TC_OP_g475__6161(.A (ADD_TC_OP_n_14), .B (d_in[3]), .CI
       (\integrator[0] [8]), .S (n_133), .CO (ADD_TC_OP_n_16));
  ADDFX2 ADD_TC_OP_g476__9315(.A (ADD_TC_OP_n_12), .B (d_in[3]), .CI
       (\integrator[0] [7]), .S (n_134), .CO (ADD_TC_OP_n_14));
  ADDFX2 ADD_TC_OP_g477__9945(.A (ADD_TC_OP_n_10), .B (d_in[3]), .CI
       (\integrator[0] [6]), .S (n_135), .CO (ADD_TC_OP_n_12));
  ADDFX2 ADD_TC_OP_g478__2883(.A (ADD_TC_OP_n_8), .B (d_in[3]), .CI
       (\integrator[0] [5]), .S (n_136), .CO (ADD_TC_OP_n_10));
  ADDFX2 ADD_TC_OP_g479__2346(.A (ADD_TC_OP_n_6), .B (d_in[3]), .CI
       (\integrator[0] [4]), .S (n_137), .CO (ADD_TC_OP_n_8));
  ADDFX2 ADD_TC_OP_g480__1666(.A (ADD_TC_OP_n_4), .B (d_in[3]), .CI
       (\integrator[0] [3]), .S (n_138), .CO (ADD_TC_OP_n_6));
  ADDFX2 ADD_TC_OP_g481__7410(.A (ADD_TC_OP_n_2), .B (d_in[2]), .CI
       (\integrator[0] [2]), .S (n_139), .CO (ADD_TC_OP_n_4));
  ADDFX2 ADD_TC_OP_g482__6417(.A (ADD_TC_OP_n_0), .B (d_in[1]), .CI
       (\integrator[0] [1]), .S (n_140), .CO (ADD_TC_OP_n_2));
  ADDHXL ADD_TC_OP_g483__5477(.A (d_in[0]), .B (\integrator[0] [0]), .S
       (n_141), .CO (ADD_TC_OP_n_0));
  XOR3X2 ADD_TC_OP_1_g1208__2398(.A (\integrator[0] [19]), .B
       (\integrator[1] [19]), .C (ADD_TC_OP_1_n_36), .Y (n_102));
  ADDFX2 ADD_TC_OP_1_g1209__5107(.A (\integrator[1] [18]), .B
       (\integrator[0] [18]), .CI (ADD_TC_OP_1_n_34), .S (n_103), .CO
       (ADD_TC_OP_1_n_36));
  ADDFX2 ADD_TC_OP_1_g1210__6260(.A (\integrator[1] [17]), .B
       (\integrator[0] [17]), .CI (ADD_TC_OP_1_n_32), .S (n_104), .CO
       (ADD_TC_OP_1_n_34));
  ADDFX2 ADD_TC_OP_1_g1211__4319(.A (\integrator[1] [16]), .B
       (\integrator[0] [16]), .CI (ADD_TC_OP_1_n_30), .S (n_105), .CO
       (ADD_TC_OP_1_n_32));
  ADDFX2 ADD_TC_OP_1_g1212__8428(.A (\integrator[1] [15]), .B
       (\integrator[0] [15]), .CI (ADD_TC_OP_1_n_28), .S (n_106), .CO
       (ADD_TC_OP_1_n_30));
  ADDFX2 ADD_TC_OP_1_g1213__5526(.A (\integrator[1] [14]), .B
       (\integrator[0] [14]), .CI (ADD_TC_OP_1_n_26), .S (n_107), .CO
       (ADD_TC_OP_1_n_28));
  ADDFX2 ADD_TC_OP_1_g1214__6783(.A (\integrator[1] [13]), .B
       (\integrator[0] [13]), .CI (ADD_TC_OP_1_n_24), .S (n_108), .CO
       (ADD_TC_OP_1_n_26));
  ADDFX2 ADD_TC_OP_1_g1215__3680(.A (\integrator[1] [12]), .B
       (\integrator[0] [12]), .CI (ADD_TC_OP_1_n_22), .S (n_109), .CO
       (ADD_TC_OP_1_n_24));
  ADDFX2 ADD_TC_OP_1_g1216__1617(.A (\integrator[1] [11]), .B
       (\integrator[0] [11]), .CI (ADD_TC_OP_1_n_20), .S (n_110), .CO
       (ADD_TC_OP_1_n_22));
  ADDFX2 ADD_TC_OP_1_g1217__2802(.A (\integrator[1] [10]), .B
       (\integrator[0] [10]), .CI (ADD_TC_OP_1_n_18), .S (n_111), .CO
       (ADD_TC_OP_1_n_20));
  ADDFX2 ADD_TC_OP_1_g1218__1705(.A (\integrator[1] [9]), .B
       (\integrator[0] [9]), .CI (ADD_TC_OP_1_n_16), .S (n_112), .CO
       (ADD_TC_OP_1_n_18));
  ADDFX2 ADD_TC_OP_1_g1219__5122(.A (\integrator[1] [8]), .B
       (\integrator[0] [8]), .CI (ADD_TC_OP_1_n_14), .S (n_113), .CO
       (ADD_TC_OP_1_n_16));
  ADDFX2 ADD_TC_OP_1_g1220__8246(.A (\integrator[1] [7]), .B
       (\integrator[0] [7]), .CI (ADD_TC_OP_1_n_12), .S (n_114), .CO
       (ADD_TC_OP_1_n_14));
  ADDFX2 ADD_TC_OP_1_g1221__7098(.A (\integrator[1] [6]), .B
       (\integrator[0] [6]), .CI (ADD_TC_OP_1_n_10), .S (n_115), .CO
       (ADD_TC_OP_1_n_12));
  ADDFX2 ADD_TC_OP_1_g1222__6131(.A (\integrator[1] [5]), .B
       (\integrator[0] [5]), .CI (ADD_TC_OP_1_n_8), .S (n_116), .CO
       (ADD_TC_OP_1_n_10));
  ADDFX2 ADD_TC_OP_1_g1223__1881(.A (\integrator[1] [4]), .B
       (\integrator[0] [4]), .CI (ADD_TC_OP_1_n_6), .S (n_117), .CO
       (ADD_TC_OP_1_n_8));
  ADDFX2 ADD_TC_OP_1_g1224__5115(.A (\integrator[1] [3]), .B
       (\integrator[0] [3]), .CI (ADD_TC_OP_1_n_4), .S (n_118), .CO
       (ADD_TC_OP_1_n_6));
  ADDFX2 ADD_TC_OP_1_g1225__7482(.A (\integrator[1] [2]), .B
       (\integrator[0] [2]), .CI (ADD_TC_OP_1_n_2), .S (n_119), .CO
       (ADD_TC_OP_1_n_4));
  ADDFX2 ADD_TC_OP_1_g1226__4733(.A (\integrator[1] [1]), .B
       (\integrator[0] [1]), .CI (ADD_TC_OP_1_n_0), .S (n_120), .CO
       (ADD_TC_OP_1_n_2));
  ADDHXL ADD_TC_OP_1_g1227__6161(.A (\integrator[1] [0]), .B
       (\integrator[0] [0]), .S (n_121), .CO (ADD_TC_OP_1_n_0));
  XOR3X2 ADD_TC_OP_2_g1208__9315(.A (\integrator[1] [19]), .B
       (\integrator[2] [19]), .C (ADD_TC_OP_2_n_36), .Y (n_82));
  ADDFX2 ADD_TC_OP_2_g1209__9945(.A (\integrator[2] [18]), .B
       (\integrator[1] [18]), .CI (ADD_TC_OP_2_n_34), .S (n_83), .CO
       (ADD_TC_OP_2_n_36));
  ADDFX2 ADD_TC_OP_2_g1210__2883(.A (\integrator[2] [17]), .B
       (\integrator[1] [17]), .CI (ADD_TC_OP_2_n_32), .S (n_84), .CO
       (ADD_TC_OP_2_n_34));
  ADDFX2 ADD_TC_OP_2_g1211__2346(.A (\integrator[2] [16]), .B
       (\integrator[1] [16]), .CI (ADD_TC_OP_2_n_30), .S (n_85), .CO
       (ADD_TC_OP_2_n_32));
  ADDFX2 ADD_TC_OP_2_g1212__1666(.A (\integrator[2] [15]), .B
       (\integrator[1] [15]), .CI (ADD_TC_OP_2_n_28), .S (n_86), .CO
       (ADD_TC_OP_2_n_30));
  ADDFX2 ADD_TC_OP_2_g1213__7410(.A (\integrator[2] [14]), .B
       (\integrator[1] [14]), .CI (ADD_TC_OP_2_n_26), .S (n_87), .CO
       (ADD_TC_OP_2_n_28));
  ADDFX2 ADD_TC_OP_2_g1214__6417(.A (\integrator[2] [13]), .B
       (\integrator[1] [13]), .CI (ADD_TC_OP_2_n_24), .S (n_88), .CO
       (ADD_TC_OP_2_n_26));
  ADDFX2 ADD_TC_OP_2_g1215__5477(.A (\integrator[2] [12]), .B
       (\integrator[1] [12]), .CI (ADD_TC_OP_2_n_22), .S (n_89), .CO
       (ADD_TC_OP_2_n_24));
  ADDFX2 ADD_TC_OP_2_g1216__2398(.A (\integrator[2] [11]), .B
       (\integrator[1] [11]), .CI (ADD_TC_OP_2_n_20), .S (n_90), .CO
       (ADD_TC_OP_2_n_22));
  ADDFX2 ADD_TC_OP_2_g1217__5107(.A (\integrator[2] [10]), .B
       (\integrator[1] [10]), .CI (ADD_TC_OP_2_n_18), .S (n_91), .CO
       (ADD_TC_OP_2_n_20));
  ADDFX2 ADD_TC_OP_2_g1218__6260(.A (\integrator[2] [9]), .B
       (\integrator[1] [9]), .CI (ADD_TC_OP_2_n_16), .S (n_92), .CO
       (ADD_TC_OP_2_n_18));
  ADDFX2 ADD_TC_OP_2_g1219__4319(.A (\integrator[2] [8]), .B
       (\integrator[1] [8]), .CI (ADD_TC_OP_2_n_14), .S (n_93), .CO
       (ADD_TC_OP_2_n_16));
  ADDFX2 ADD_TC_OP_2_g1220__8428(.A (\integrator[2] [7]), .B
       (\integrator[1] [7]), .CI (ADD_TC_OP_2_n_12), .S (n_94), .CO
       (ADD_TC_OP_2_n_14));
  ADDFX2 ADD_TC_OP_2_g1221__5526(.A (\integrator[2] [6]), .B
       (\integrator[1] [6]), .CI (ADD_TC_OP_2_n_10), .S (n_95), .CO
       (ADD_TC_OP_2_n_12));
  ADDFX2 ADD_TC_OP_2_g1222__6783(.A (\integrator[2] [5]), .B
       (\integrator[1] [5]), .CI (ADD_TC_OP_2_n_8), .S (n_96), .CO
       (ADD_TC_OP_2_n_10));
  ADDFX2 ADD_TC_OP_2_g1223__3680(.A (\integrator[2] [4]), .B
       (\integrator[1] [4]), .CI (ADD_TC_OP_2_n_6), .S (n_97), .CO
       (ADD_TC_OP_2_n_8));
  ADDFX2 ADD_TC_OP_2_g1224__1617(.A (\integrator[2] [3]), .B
       (\integrator[1] [3]), .CI (ADD_TC_OP_2_n_4), .S (n_98), .CO
       (ADD_TC_OP_2_n_6));
  ADDFX2 ADD_TC_OP_2_g1225__2802(.A (\integrator[2] [2]), .B
       (\integrator[1] [2]), .CI (ADD_TC_OP_2_n_2), .S (n_99), .CO
       (ADD_TC_OP_2_n_4));
  ADDFX2 ADD_TC_OP_2_g1226__1705(.A (\integrator[2] [1]), .B
       (\integrator[1] [1]), .CI (ADD_TC_OP_2_n_0), .S (n_100), .CO
       (ADD_TC_OP_2_n_2));
  ADDHXL ADD_TC_OP_2_g1227__5122(.A (\integrator[2] [0]), .B
       (\integrator[1] [0]), .S (n_101), .CO (ADD_TC_OP_2_n_0));
  XOR3X2 ADD_TC_OP_3_g1208__8246(.A (\integrator[2] [19]), .B
       (\integrator[3] [19]), .C (ADD_TC_OP_3_n_36), .Y (n_62));
  ADDFX2 ADD_TC_OP_3_g1209__7098(.A (\integrator[3] [18]), .B
       (\integrator[2] [18]), .CI (ADD_TC_OP_3_n_34), .S (n_63), .CO
       (ADD_TC_OP_3_n_36));
  ADDFX2 ADD_TC_OP_3_g1210__6131(.A (\integrator[3] [17]), .B
       (\integrator[2] [17]), .CI (ADD_TC_OP_3_n_32), .S (n_64), .CO
       (ADD_TC_OP_3_n_34));
  ADDFX2 ADD_TC_OP_3_g1211__1881(.A (\integrator[3] [16]), .B
       (\integrator[2] [16]), .CI (ADD_TC_OP_3_n_30), .S (n_65), .CO
       (ADD_TC_OP_3_n_32));
  ADDFX2 ADD_TC_OP_3_g1212__5115(.A (\integrator[3] [15]), .B
       (\integrator[2] [15]), .CI (ADD_TC_OP_3_n_28), .S (n_66), .CO
       (ADD_TC_OP_3_n_30));
  ADDFX2 ADD_TC_OP_3_g1213__7482(.A (\integrator[3] [14]), .B
       (\integrator[2] [14]), .CI (ADD_TC_OP_3_n_26), .S (n_67), .CO
       (ADD_TC_OP_3_n_28));
  ADDFX2 ADD_TC_OP_3_g1214__4733(.A (\integrator[3] [13]), .B
       (\integrator[2] [13]), .CI (ADD_TC_OP_3_n_24), .S (n_68), .CO
       (ADD_TC_OP_3_n_26));
  ADDFX2 ADD_TC_OP_3_g1215__6161(.A (\integrator[3] [12]), .B
       (\integrator[2] [12]), .CI (ADD_TC_OP_3_n_22), .S (n_69), .CO
       (ADD_TC_OP_3_n_24));
  ADDFX2 ADD_TC_OP_3_g1216__9315(.A (\integrator[3] [11]), .B
       (\integrator[2] [11]), .CI (ADD_TC_OP_3_n_20), .S (n_70), .CO
       (ADD_TC_OP_3_n_22));
  ADDFX2 ADD_TC_OP_3_g1217__9945(.A (\integrator[3] [10]), .B
       (\integrator[2] [10]), .CI (ADD_TC_OP_3_n_18), .S (n_71), .CO
       (ADD_TC_OP_3_n_20));
  ADDFX2 ADD_TC_OP_3_g1218__2883(.A (\integrator[3] [9]), .B
       (\integrator[2] [9]), .CI (ADD_TC_OP_3_n_16), .S (n_72), .CO
       (ADD_TC_OP_3_n_18));
  ADDFX2 ADD_TC_OP_3_g1219__2346(.A (\integrator[3] [8]), .B
       (\integrator[2] [8]), .CI (ADD_TC_OP_3_n_14), .S (n_73), .CO
       (ADD_TC_OP_3_n_16));
  ADDFX2 ADD_TC_OP_3_g1220__1666(.A (\integrator[3] [7]), .B
       (\integrator[2] [7]), .CI (ADD_TC_OP_3_n_12), .S (n_74), .CO
       (ADD_TC_OP_3_n_14));
  ADDFX2 ADD_TC_OP_3_g1221__7410(.A (\integrator[3] [6]), .B
       (\integrator[2] [6]), .CI (ADD_TC_OP_3_n_10), .S (n_75), .CO
       (ADD_TC_OP_3_n_12));
  ADDFX2 ADD_TC_OP_3_g1222__6417(.A (\integrator[3] [5]), .B
       (\integrator[2] [5]), .CI (ADD_TC_OP_3_n_8), .S (n_76), .CO
       (ADD_TC_OP_3_n_10));
  ADDFX2 ADD_TC_OP_3_g1223__5477(.A (\integrator[3] [4]), .B
       (\integrator[2] [4]), .CI (ADD_TC_OP_3_n_6), .S (n_77), .CO
       (ADD_TC_OP_3_n_8));
  ADDFX2 ADD_TC_OP_3_g1224__2398(.A (\integrator[3] [3]), .B
       (\integrator[2] [3]), .CI (ADD_TC_OP_3_n_4), .S (n_78), .CO
       (ADD_TC_OP_3_n_6));
  ADDFX2 ADD_TC_OP_3_g1225__5107(.A (\integrator[3] [2]), .B
       (\integrator[2] [2]), .CI (ADD_TC_OP_3_n_2), .S (n_79), .CO
       (ADD_TC_OP_3_n_4));
  ADDFX2 ADD_TC_OP_3_g1226__6260(.A (\integrator[3] [1]), .B
       (\integrator[2] [1]), .CI (ADD_TC_OP_3_n_0), .S (n_80), .CO
       (ADD_TC_OP_3_n_2));
  ADDHXL ADD_TC_OP_3_g1227__4319(.A (\integrator[3] [0]), .B
       (\integrator[2] [0]), .S (n_81), .CO (ADD_TC_OP_3_n_0));
  XNOR3X2 sub_72_24_g1269__8428(.A (\d_comb[0][1] [19]), .B
       (d_tmp[19]), .C (sub_72_24_n_55), .Y (\comb[0] [19]));
  ADDFX2 sub_72_24_g1270__5526(.A (sub_72_24_n_5), .B (d_tmp[18]), .CI
       (sub_72_24_n_53), .S (\comb[0] [18]), .CO (sub_72_24_n_55));
  ADDFX2 sub_72_24_g1271__6783(.A (sub_72_24_n_14), .B (d_tmp[17]), .CI
       (sub_72_24_n_51), .S (\comb[0] [17]), .CO (sub_72_24_n_53));
  ADDFX2 sub_72_24_g1272__3680(.A (sub_72_24_n_8), .B (d_tmp[16]), .CI
       (sub_72_24_n_49), .S (\comb[0] [16]), .CO (sub_72_24_n_51));
  ADDFX2 sub_72_24_g1273__1617(.A (sub_72_24_n_4), .B (d_tmp[15]), .CI
       (sub_72_24_n_47), .S (\comb[0] [15]), .CO (sub_72_24_n_49));
  ADDFX2 sub_72_24_g1274__2802(.A (sub_72_24_n_17), .B (d_tmp[14]), .CI
       (sub_72_24_n_45), .S (\comb[0] [14]), .CO (sub_72_24_n_47));
  ADDFX2 sub_72_24_g1275__1705(.A (sub_72_24_n_15), .B (d_tmp[13]), .CI
       (sub_72_24_n_43), .S (\comb[0] [13]), .CO (sub_72_24_n_45));
  ADDFX2 sub_72_24_g1276__5122(.A (sub_72_24_n_11), .B (d_tmp[12]), .CI
       (sub_72_24_n_41), .S (\comb[0] [12]), .CO (sub_72_24_n_43));
  ADDFX2 sub_72_24_g1277__8246(.A (sub_72_24_n_12), .B (d_tmp[11]), .CI
       (sub_72_24_n_39), .S (\comb[0] [11]), .CO (sub_72_24_n_41));
  ADDFX2 sub_72_24_g1278__7098(.A (sub_72_24_n_3), .B (d_tmp[10]), .CI
       (sub_72_24_n_37), .S (\comb[0] [10]), .CO (sub_72_24_n_39));
  ADDFX2 sub_72_24_g1279__6131(.A (sub_72_24_n_13), .B (d_tmp[9]), .CI
       (sub_72_24_n_35), .S (\comb[0] [9]), .CO (sub_72_24_n_37));
  ADDFX2 sub_72_24_g1280__1881(.A (sub_72_24_n_6), .B (d_tmp[8]), .CI
       (sub_72_24_n_33), .S (\comb[0] [8]), .CO (sub_72_24_n_35));
  ADDFX2 sub_72_24_g1281__5115(.A (sub_72_24_n_16), .B (d_tmp[7]), .CI
       (sub_72_24_n_31), .S (\comb[0] [7]), .CO (sub_72_24_n_33));
  ADDFX2 sub_72_24_g1282__7482(.A (sub_72_24_n_10), .B (d_tmp[6]), .CI
       (sub_72_24_n_29), .S (\comb[0] [6]), .CO (sub_72_24_n_31));
  ADDFX2 sub_72_24_g1283__4733(.A (sub_72_24_n_0), .B (d_tmp[5]), .CI
       (sub_72_24_n_27), .S (\comb[0] [5]), .CO (sub_72_24_n_29));
  ADDFX2 sub_72_24_g1284__6161(.A (sub_72_24_n_1), .B (d_tmp[4]), .CI
       (sub_72_24_n_25), .S (\comb[0] [4]), .CO (sub_72_24_n_27));
  ADDFX2 sub_72_24_g1285__9315(.A (sub_72_24_n_9), .B (d_tmp[3]), .CI
       (sub_72_24_n_23), .S (\comb[0] [3]), .CO (sub_72_24_n_25));
  ADDFX2 sub_72_24_g1286__9945(.A (sub_72_24_n_2), .B (d_tmp[2]), .CI
       (sub_72_24_n_21), .S (\comb[0] [2]), .CO (sub_72_24_n_23));
  ADDFX2 sub_72_24_g1287__2883(.A (sub_72_24_n_18), .B (d_tmp[1]), .CI
       (sub_72_24_n_19), .S (\comb[0] [1]), .CO (sub_72_24_n_21));
  OAI21XL sub_72_24_g1288__2346(.A0 (sub_72_24_n_7), .A1
       (\d_comb[0][1] [0]), .B0 (sub_72_24_n_19), .Y (\comb[0] [0]));
  NAND2X1 sub_72_24_g1289__1666(.A (sub_72_24_n_7), .B
       (\d_comb[0][1] [0]), .Y (sub_72_24_n_19));
  DFFRX1 \d_comb_reg[2][1][1] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [1]), .Q (\d_comb[2][1] [1]), .QN
       (sub_75_30_I2_n_695));
  DFFRX1 \d_comb_reg[2][1][14] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [14]), .Q (\d_comb[2][1] [14]), .QN
       (sub_75_30_I2_n_696));
  DFFRX1 \d_comb_reg[2][1][7] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [7]), .Q (\d_comb[2][1] [7]), .QN
       (sub_75_30_I2_n_698));
  DFFRX1 \d_comb_reg[2][1][13] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [13]), .Q (\d_comb[2][1] [13]), .QN
       (sub_75_30_I2_n_699));
  DFFRX1 \d_comb_reg[2][1][17] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [17]), .Q (\d_comb[2][1] [17]), .QN
       (sub_75_30_I2_n_700));
  DFFRX1 \d_comb_reg[2][1][9] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [9]), .Q (\d_comb[2][1] [9]), .QN
       (sub_75_30_I2_n_701));
  DFFRX1 \d_comb_reg[2][1][11] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [11]), .Q (\d_comb[2][1] [11]), .QN
       (sub_75_30_I2_n_702));
  DFFRX1 \d_comb_reg[2][1][12] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [12]), .Q (\d_comb[2][1] [12]), .QN
       (sub_75_30_I2_n_703));
  DFFRX1 \d_comb_reg[2][1][6] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [6]), .Q (\d_comb[2][1] [6]), .QN
       (sub_75_30_I2_n_704));
  DFFRX1 \d_comb_reg[2][1][3] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [3]), .Q (\d_comb[2][1] [3]), .QN
       (sub_75_30_I2_n_705));
  DFFRX1 \d_comb_reg[2][1][16] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [16]), .Q (\d_comb[2][1] [16]), .QN
       (sub_75_30_I2_n_706));
  DFFRX1 \d_comb_reg[2][1][8] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [8]), .Q (\d_comb[2][1] [8]), .QN
       (sub_75_30_I2_n_708));
  DFFRX1 \d_comb_reg[2][1][18] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [18]), .Q (\d_comb[2][1] [18]), .QN
       (sub_75_30_I2_n_709));
  DFFRX1 \d_comb_reg[2][1][15] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [15]), .Q (\d_comb[2][1] [15]), .QN
       (sub_75_30_I2_n_710));
  DFFRX1 \d_comb_reg[2][1][10] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [10]), .Q (\d_comb[2][1] [10]), .QN
       (sub_75_30_I2_n_711));
  DFFRX1 \d_comb_reg[2][1][2] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [2]), .Q (\d_comb[2][1] [2]), .QN
       (sub_75_30_I2_n_712));
  DFFRX1 \d_comb_reg[2][1][4] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [4]), .Q (\d_comb[2][1] [4]), .QN
       (sub_75_30_I2_n_713));
  DFFRX1 \d_comb_reg[2][1][5] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[2][0] [5]), .Q (\d_comb[2][1] [5]), .QN
       (sub_75_30_I2_n_714));
  DFFRX1 \d_comb_reg[1][1][1] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [1]), .Q (\d_comb[1][1] [1]), .QN
       (sub_75_30_I1_n_695));
  DFFRX1 \d_comb_reg[1][1][14] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [14]), .Q (\d_comb[1][1] [14]), .QN
       (sub_75_30_I1_n_696));
  DFFRX1 \d_comb_reg[1][1][7] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [7]), .Q (\d_comb[1][1] [7]), .QN
       (sub_75_30_I1_n_698));
  DFFRX1 \d_comb_reg[1][1][13] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [13]), .Q (\d_comb[1][1] [13]), .QN
       (sub_75_30_I1_n_699));
  DFFRX1 \d_comb_reg[1][1][17] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [17]), .Q (\d_comb[1][1] [17]), .QN
       (sub_75_30_I1_n_700));
  DFFRX1 \d_comb_reg[1][1][9] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [9]), .Q (\d_comb[1][1] [9]), .QN
       (sub_75_30_I1_n_701));
  DFFRX1 \d_comb_reg[1][1][11] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [11]), .Q (\d_comb[1][1] [11]), .QN
       (sub_75_30_I1_n_702));
  DFFRX1 \d_comb_reg[1][1][12] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [12]), .Q (\d_comb[1][1] [12]), .QN
       (sub_75_30_I1_n_703));
  DFFRX1 \d_comb_reg[1][1][6] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [6]), .Q (\d_comb[1][1] [6]), .QN
       (sub_75_30_I1_n_704));
  DFFRX1 \d_comb_reg[1][1][3] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [3]), .Q (\d_comb[1][1] [3]), .QN
       (sub_75_30_I1_n_705));
  DFFRX1 \d_comb_reg[1][1][16] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [16]), .Q (\d_comb[1][1] [16]), .QN
       (sub_75_30_I1_n_706));
  DFFRX1 \d_comb_reg[1][1][8] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [8]), .Q (\d_comb[1][1] [8]), .QN
       (sub_75_30_I1_n_708));
  DFFRX1 \d_comb_reg[1][1][18] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [18]), .Q (\d_comb[1][1] [18]), .QN
       (sub_75_30_I1_n_709));
  DFFRX1 \d_comb_reg[1][1][15] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [15]), .Q (\d_comb[1][1] [15]), .QN
       (sub_75_30_I1_n_710));
  DFFRX1 \d_comb_reg[1][1][10] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [10]), .Q (\d_comb[1][1] [10]), .QN
       (sub_75_30_I1_n_711));
  DFFRX1 \d_comb_reg[1][1][2] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [2]), .Q (\d_comb[1][1] [2]), .QN
       (sub_75_30_I1_n_712));
  DFFRX1 \d_comb_reg[1][1][4] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [4]), .Q (\d_comb[1][1] [4]), .QN
       (sub_75_30_I1_n_713));
  DFFRX1 \d_comb_reg[1][1][5] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[1][0] [5]), .Q (\d_comb[1][1] [5]), .QN
       (sub_75_30_I1_n_714));
  DFFRX1 \d_comb_reg[0][1][1] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [1]), .Q (\d_comb[0][1] [1]), .QN
       (sub_72_24_n_18));
  DFFRX1 \d_comb_reg[0][1][14] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [14]), .Q (\d_comb[0][1] [14]), .QN
       (sub_72_24_n_17));
  DFFRX1 \d_comb_reg[0][1][7] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [7]), .Q (\d_comb[0][1] [7]), .QN
       (sub_72_24_n_16));
  DFFRX1 \d_comb_reg[0][1][13] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [13]), .Q (\d_comb[0][1] [13]), .QN
       (sub_72_24_n_15));
  DFFRX1 \d_comb_reg[0][1][17] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [17]), .Q (\d_comb[0][1] [17]), .QN
       (sub_72_24_n_14));
  DFFRX1 \d_comb_reg[0][1][9] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [9]), .Q (\d_comb[0][1] [9]), .QN
       (sub_72_24_n_13));
  DFFRX1 \d_comb_reg[0][1][11] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [11]), .Q (\d_comb[0][1] [11]), .QN
       (sub_72_24_n_12));
  DFFRX1 \d_comb_reg[0][1][12] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [12]), .Q (\d_comb[0][1] [12]), .QN
       (sub_72_24_n_11));
  DFFRX1 \d_comb_reg[0][1][6] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [6]), .Q (\d_comb[0][1] [6]), .QN
       (sub_72_24_n_10));
  DFFRX1 \d_comb_reg[0][1][3] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [3]), .Q (\d_comb[0][1] [3]), .QN
       (sub_72_24_n_9));
  DFFRX1 \d_comb_reg[0][1][16] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [16]), .Q (\d_comb[0][1] [16]), .QN
       (sub_72_24_n_8));
  DFFRX1 \d_tmp_reg[0] (.RN (n_0), .CK (rc_gclk_1229), .D
       (\integrator[3] [0]), .Q (d_tmp[0]), .QN (sub_72_24_n_7));
  DFFRX1 \d_comb_reg[0][1][8] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [8]), .Q (\d_comb[0][1] [8]), .QN
       (sub_72_24_n_6));
  DFFRX1 \d_comb_reg[0][1][18] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [18]), .Q (\d_comb[0][1] [18]), .QN
       (sub_72_24_n_5));
  DFFRX1 \d_comb_reg[0][1][15] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [15]), .Q (\d_comb[0][1] [15]), .QN
       (sub_72_24_n_4));
  DFFRX1 \d_comb_reg[0][1][10] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [10]), .Q (\d_comb[0][1] [10]), .QN
       (sub_72_24_n_3));
  DFFRX1 \d_comb_reg[0][1][2] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [2]), .Q (\d_comb[0][1] [2]), .QN
       (sub_72_24_n_2));
  DFFRX1 \d_comb_reg[0][1][4] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [4]), .Q (\d_comb[0][1] [4]), .QN
       (sub_72_24_n_1));
  DFFRX1 \d_comb_reg[0][1][5] (.RN (n_0), .CK (rc_gclk), .D
       (\d_comb[0][0] [5]), .Q (\d_comb[0][1] [5]), .QN
       (sub_72_24_n_0));
endmodule

