
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point d_in[3] d_in[3] -type PI PI
add mapped point d_in[2] d_in[2] -type PI PI
add mapped point d_in[1] d_in[1] -type PI PI
add mapped point d_in[0] d_in[0] -type PI PI
add mapped point ce_1 ce_1 -type PI PI
add mapped point ce_2 ce_2 -type PI PI

//output ports
add mapped point d_out[3] d_out[3] -type PO PO
add mapped point d_out[2] d_out[2] -type PO PO
add mapped point d_out[1] d_out[1] -type PO PO
add mapped point d_out[0] d_out[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point d_comb[1][0][0]/q d_comb_reg[1][0][0]/Q -type DFF DFF
add mapped point d_comb[1][0][1]/q d_comb_reg[1][0][1]/Q -type DFF DFF
add mapped point d_comb[1][0][2]/q d_comb_reg[1][0][2]/Q -type DFF DFF
add mapped point d_comb[1][0][3]/q d_comb_reg[1][0][3]/Q -type DFF DFF
add mapped point d_comb[1][0][4]/q d_comb_reg[1][0][4]/Q -type DFF DFF
add mapped point d_comb[1][0][5]/q d_comb_reg[1][0][5]/Q -type DFF DFF
add mapped point d_comb[1][0][6]/q d_comb_reg[1][0][6]/Q -type DFF DFF
add mapped point d_comb[1][0][7]/q d_comb_reg[1][0][7]/Q -type DFF DFF
add mapped point d_comb[1][0][8]/q d_comb_reg[1][0][8]/Q -type DFF DFF
add mapped point d_comb[1][0][9]/q d_comb_reg[1][0][9]/Q -type DFF DFF
add mapped point d_comb[1][0][10]/q d_comb_reg[1][0][10]/Q -type DFF DFF
add mapped point d_comb[1][0][11]/q d_comb_reg[1][0][11]/Q -type DFF DFF
add mapped point d_comb[1][0][12]/q d_comb_reg[1][0][12]/Q -type DFF DFF
add mapped point d_comb[1][0][13]/q d_comb_reg[1][0][13]/Q -type DFF DFF
add mapped point d_comb[1][0][14]/q d_comb_reg[1][0][14]/Q -type DFF DFF
add mapped point d_comb[1][0][15]/q d_comb_reg[1][0][15]/Q -type DFF DFF
add mapped point d_comb[1][0][16]/q d_comb_reg[1][0][16]/Q -type DFF DFF
add mapped point d_comb[1][0][17]/q d_comb_reg[1][0][17]/Q -type DFF DFF
add mapped point d_comb[1][0][18]/q d_comb_reg[1][0][18]/Q -type DFF DFF
add mapped point d_comb[1][0][19]/q d_comb_reg[1][0][19]/Q -type DFF DFF
add mapped point d_comb[2][0][0]/q d_comb_reg[2][0][0]/Q -type DFF DFF
add mapped point d_comb[2][0][1]/q d_comb_reg[2][0][1]/Q -type DFF DFF
add mapped point d_comb[2][0][2]/q d_comb_reg[2][0][2]/Q -type DFF DFF
add mapped point d_comb[2][0][3]/q d_comb_reg[2][0][3]/Q -type DFF DFF
add mapped point d_comb[2][0][4]/q d_comb_reg[2][0][4]/Q -type DFF DFF
add mapped point d_comb[2][0][5]/q d_comb_reg[2][0][5]/Q -type DFF DFF
add mapped point d_comb[2][0][6]/q d_comb_reg[2][0][6]/Q -type DFF DFF
add mapped point d_comb[2][0][7]/q d_comb_reg[2][0][7]/Q -type DFF DFF
add mapped point d_comb[2][0][8]/q d_comb_reg[2][0][8]/Q -type DFF DFF
add mapped point d_comb[2][0][9]/q d_comb_reg[2][0][9]/Q -type DFF DFF
add mapped point d_comb[2][0][10]/q d_comb_reg[2][0][10]/Q -type DFF DFF
add mapped point d_comb[2][0][11]/q d_comb_reg[2][0][11]/Q -type DFF DFF
add mapped point d_comb[2][0][12]/q d_comb_reg[2][0][12]/Q -type DFF DFF
add mapped point d_comb[2][0][13]/q d_comb_reg[2][0][13]/Q -type DFF DFF
add mapped point d_comb[2][0][14]/q d_comb_reg[2][0][14]/Q -type DFF DFF
add mapped point d_comb[2][0][15]/q d_comb_reg[2][0][15]/Q -type DFF DFF
add mapped point d_comb[2][0][16]/q d_comb_reg[2][0][16]/Q -type DFF DFF
add mapped point d_comb[2][0][17]/q d_comb_reg[2][0][17]/Q -type DFF DFF
add mapped point d_comb[2][0][18]/q d_comb_reg[2][0][18]/Q -type DFF DFF
add mapped point d_comb[2][0][19]/q d_comb_reg[2][0][19]/Q -type DFF DFF
add mapped point d_comb[3][0][0]/q d_comb_reg[3][0][0]/Q -type DFF DFF
add mapped point d_comb[3][0][1]/q d_comb_reg[3][0][1]/Q -type DFF DFF
add mapped point d_comb[3][0][2]/q d_comb_reg[3][0][2]/Q -type DFF DFF
add mapped point d_comb[3][0][3]/q d_comb_reg[3][0][3]/Q -type DFF DFF
add mapped point d_comb[3][0][4]/q d_comb_reg[3][0][4]/Q -type DFF DFF
add mapped point d_comb[3][0][5]/q d_comb_reg[3][0][5]/Q -type DFF DFF
add mapped point d_comb[3][0][6]/q d_comb_reg[3][0][6]/Q -type DFF DFF
add mapped point d_comb[3][0][7]/q d_comb_reg[3][0][7]/Q -type DFF DFF
add mapped point d_comb[3][0][8]/q d_comb_reg[3][0][8]/Q -type DFF DFF
add mapped point d_comb[3][0][9]/q d_comb_reg[3][0][9]/Q -type DFF DFF
add mapped point d_comb[3][0][10]/q d_comb_reg[3][0][10]/Q -type DFF DFF
add mapped point d_comb[3][0][11]/q d_comb_reg[3][0][11]/Q -type DFF DFF
add mapped point d_comb[3][0][12]/q d_comb_reg[3][0][12]/Q -type DFF DFF
add mapped point d_comb[3][0][13]/q d_comb_reg[3][0][13]/Q -type DFF DFF
add mapped point d_comb[3][0][14]/q d_comb_reg[3][0][14]/Q -type DFF DFF
add mapped point d_comb[3][0][15]/q d_comb_reg[3][0][15]/Q -type DFF DFF
add mapped point d_comb[3][0][16]/q d_comb_reg[3][0][16]/Q -type DFF DFF
add mapped point d_comb[3][0][17]/q d_comb_reg[3][0][17]/Q -type DFF DFF
add mapped point d_comb[3][0][18]/q d_comb_reg[3][0][18]/Q -type DFF DFF
add mapped point d_comb[3][0][19]/q d_comb_reg[3][0][19]/Q -type DFF DFF
add mapped point d_comb[3][1][0]/q d_comb_reg[3][1][0]/Q -type DFF DFF
add mapped point d_comb[3][1][1]/q d_comb_reg[3][1][1]/Q -type DFF DFF
add mapped point d_comb[3][1][2]/q d_comb_reg[3][1][2]/Q -type DFF DFF
add mapped point d_comb[3][1][3]/q d_comb_reg[3][1][3]/Q -type DFF DFF
add mapped point d_comb[3][1][4]/q d_comb_reg[3][1][4]/Q -type DFF DFF
add mapped point d_comb[3][1][5]/q d_comb_reg[3][1][5]/Q -type DFF DFF
add mapped point d_comb[3][1][6]/q d_comb_reg[3][1][6]/Q -type DFF DFF
add mapped point d_comb[3][1][7]/q d_comb_reg[3][1][7]/Q -type DFF DFF
add mapped point d_comb[3][1][8]/q d_comb_reg[3][1][8]/Q -type DFF DFF
add mapped point d_comb[3][1][9]/q d_comb_reg[3][1][9]/Q -type DFF DFF
add mapped point d_comb[3][1][10]/q d_comb_reg[3][1][10]/Q -type DFF DFF
add mapped point d_comb[3][1][11]/q d_comb_reg[3][1][11]/Q -type DFF DFF
add mapped point d_comb[3][1][12]/q d_comb_reg[3][1][12]/Q -type DFF DFF
add mapped point d_comb[3][1][13]/q d_comb_reg[3][1][13]/Q -type DFF DFF
add mapped point d_comb[3][1][14]/q d_comb_reg[3][1][14]/Q -type DFF DFF
add mapped point d_comb[3][1][15]/q d_comb_reg[3][1][15]/Q -type DFF DFF
add mapped point d_comb[3][1][16]/q d_comb_reg[3][1][16]/Q -type DFF DFF
add mapped point d_comb[3][1][17]/q d_comb_reg[3][1][17]/Q -type DFF DFF
add mapped point d_comb[3][1][18]/q d_comb_reg[3][1][18]/Q -type DFF DFF
add mapped point d_comb[3][1][19]/q d_comb_reg[3][1][19]/Q -type DFF DFF
add mapped point d_comb[0][1][0]/q d_comb_reg[0][1][0]/Q -type DFF DFF
add mapped point d_comb[0][1][19]/q d_comb_reg[0][1][19]/Q -type DFF DFF
add mapped point d_comb[0][0][2]/q d_comb_reg[0][0][2]/Q -type DFF DFF
add mapped point d_comb[0][0][3]/q d_comb_reg[0][0][3]/Q -type DFF DFF
add mapped point d_comb[0][0][4]/q d_comb_reg[0][0][4]/Q -type DFF DFF
add mapped point d_comb[0][0][5]/q d_comb_reg[0][0][5]/Q -type DFF DFF
add mapped point d_comb[0][0][6]/q d_comb_reg[0][0][6]/Q -type DFF DFF
add mapped point d_comb[0][0][7]/q d_comb_reg[0][0][7]/Q -type DFF DFF
add mapped point d_comb[0][0][8]/q d_comb_reg[0][0][8]/Q -type DFF DFF
add mapped point d_comb[0][0][9]/q d_comb_reg[0][0][9]/Q -type DFF DFF
add mapped point d_comb[0][0][10]/q d_comb_reg[0][0][10]/Q -type DFF DFF
add mapped point d_comb[0][0][11]/q d_comb_reg[0][0][11]/Q -type DFF DFF
add mapped point d_comb[0][0][12]/q d_comb_reg[0][0][12]/Q -type DFF DFF
add mapped point d_comb[0][0][13]/q d_comb_reg[0][0][13]/Q -type DFF DFF
add mapped point d_comb[0][0][14]/q d_comb_reg[0][0][14]/Q -type DFF DFF
add mapped point d_comb[0][0][0]/q d_comb_reg[0][0][0]/Q -type DFF DFF
add mapped point d_comb[0][0][17]/q d_comb_reg[0][0][17]/Q -type DFF DFF
add mapped point d_comb[0][0][18]/q d_comb_reg[0][0][18]/Q -type DFF DFF
add mapped point d_comb[0][0][1]/q d_comb_reg[0][0][1]/Q -type DFF DFF
add mapped point d_comb[0][0][19]/q d_comb_reg[0][0][19]/Q -type DFF DFF
add mapped point d_comb[0][0][15]/q d_comb_reg[0][0][15]/Q -type DFF DFF
add mapped point d_comb[0][0][16]/q d_comb_reg[0][0][16]/Q -type DFF DFF
add mapped point d_tmp[18]/q d_tmp_reg[18]/Q -type DFF DFF
add mapped point d_tmp[14]/q d_tmp_reg[14]/Q -type DFF DFF
add mapped point d_tmp[6]/q d_tmp_reg[6]/Q -type DFF DFF
add mapped point d_tmp[1]/q d_tmp_reg[1]/Q -type DFF DFF
add mapped point d_tmp[2]/q d_tmp_reg[2]/Q -type DFF DFF
add mapped point d_tmp[3]/q d_tmp_reg[3]/Q -type DFF DFF
add mapped point d_tmp[4]/q d_tmp_reg[4]/Q -type DFF DFF
add mapped point d_tmp[5]/q d_tmp_reg[5]/Q -type DFF DFF
add mapped point d_tmp[7]/q d_tmp_reg[7]/Q -type DFF DFF
add mapped point d_tmp[8]/q d_tmp_reg[8]/Q -type DFF DFF
add mapped point d_tmp[9]/q d_tmp_reg[9]/Q -type DFF DFF
add mapped point d_tmp[10]/q d_tmp_reg[10]/Q -type DFF DFF
add mapped point d_tmp[11]/q d_tmp_reg[11]/Q -type DFF DFF
add mapped point d_tmp[12]/q d_tmp_reg[12]/Q -type DFF DFF
add mapped point d_tmp[13]/q d_tmp_reg[13]/Q -type DFF DFF
add mapped point d_tmp[15]/q d_tmp_reg[15]/Q -type DFF DFF
add mapped point d_tmp[16]/q d_tmp_reg[16]/Q -type DFF DFF
add mapped point d_tmp[17]/q d_tmp_reg[17]/Q -type DFF DFF
add mapped point d_tmp[19]/q d_tmp_reg[19]/Q -type DFF DFF
add mapped point integrator[0][17]/q integrator_reg[0][17]/Q -type DFF DFF
add mapped point integrator[0][1]/q integrator_reg[0][1]/Q -type DFF DFF
add mapped point integrator[0][2]/q integrator_reg[0][2]/Q -type DFF DFF
add mapped point integrator[0][3]/q integrator_reg[0][3]/Q -type DFF DFF
add mapped point integrator[0][4]/q integrator_reg[0][4]/Q -type DFF DFF
add mapped point integrator[3][15]/q integrator_reg[3][15]/Q -type DFF DFF
add mapped point integrator[0][5]/q integrator_reg[0][5]/Q -type DFF DFF
add mapped point integrator[0][6]/q integrator_reg[0][6]/Q -type DFF DFF
add mapped point integrator[0][7]/q integrator_reg[0][7]/Q -type DFF DFF
add mapped point integrator[3][11]/q integrator_reg[3][11]/Q -type DFF DFF
add mapped point integrator[0][8]/q integrator_reg[0][8]/Q -type DFF DFF
add mapped point integrator[0][9]/q integrator_reg[0][9]/Q -type DFF DFF
add mapped point integrator[0][10]/q integrator_reg[0][10]/Q -type DFF DFF
add mapped point integrator[3][7]/q integrator_reg[3][7]/Q -type DFF DFF
add mapped point integrator[0][11]/q integrator_reg[0][11]/Q -type DFF DFF
add mapped point integrator[0][12]/q integrator_reg[0][12]/Q -type DFF DFF
add mapped point integrator[0][13]/q integrator_reg[0][13]/Q -type DFF DFF
add mapped point integrator[0][14]/q integrator_reg[0][14]/Q -type DFF DFF
add mapped point integrator[0][15]/q integrator_reg[0][15]/Q -type DFF DFF
add mapped point integrator[0][16]/q integrator_reg[0][16]/Q -type DFF DFF
add mapped point integrator[0][0]/q integrator_reg[0][0]/Q -type DFF DFF
add mapped point integrator[2][19]/q integrator_reg[2][19]/Q -type DFF DFF
add mapped point integrator[0][18]/q integrator_reg[0][18]/Q -type DFF DFF
add mapped point integrator[0][19]/q integrator_reg[0][19]/Q -type DFF DFF
add mapped point integrator[1][0]/q integrator_reg[1][0]/Q -type DFF DFF
add mapped point integrator[2][15]/q integrator_reg[2][15]/Q -type DFF DFF
add mapped point integrator[1][1]/q integrator_reg[1][1]/Q -type DFF DFF
add mapped point integrator[1][2]/q integrator_reg[1][2]/Q -type DFF DFF
add mapped point integrator[1][3]/q integrator_reg[1][3]/Q -type DFF DFF
add mapped point integrator[2][11]/q integrator_reg[2][11]/Q -type DFF DFF
add mapped point integrator[1][4]/q integrator_reg[1][4]/Q -type DFF DFF
add mapped point integrator[1][5]/q integrator_reg[1][5]/Q -type DFF DFF
add mapped point integrator[1][6]/q integrator_reg[1][6]/Q -type DFF DFF
add mapped point integrator[1][7]/q integrator_reg[1][7]/Q -type DFF DFF
add mapped point integrator[1][8]/q integrator_reg[1][8]/Q -type DFF DFF
add mapped point integrator[1][9]/q integrator_reg[1][9]/Q -type DFF DFF
add mapped point integrator[1][10]/q integrator_reg[1][10]/Q -type DFF DFF
add mapped point integrator[2][3]/q integrator_reg[2][3]/Q -type DFF DFF
add mapped point integrator[1][11]/q integrator_reg[1][11]/Q -type DFF DFF
add mapped point integrator[1][12]/q integrator_reg[1][12]/Q -type DFF DFF
add mapped point integrator[2][16]/q integrator_reg[2][16]/Q -type DFF DFF
add mapped point integrator[1][14]/q integrator_reg[1][14]/Q -type DFF DFF
add mapped point integrator[1][15]/q integrator_reg[1][15]/Q -type DFF DFF
add mapped point integrator[1][16]/q integrator_reg[1][16]/Q -type DFF DFF
add mapped point integrator[1][17]/q integrator_reg[1][17]/Q -type DFF DFF
add mapped point integrator[1][18]/q integrator_reg[1][18]/Q -type DFF DFF
add mapped point integrator[1][19]/q integrator_reg[1][19]/Q -type DFF DFF
add mapped point integrator[2][0]/q integrator_reg[2][0]/Q -type DFF DFF
add mapped point integrator[2][1]/q integrator_reg[2][1]/Q -type DFF DFF
add mapped point integrator[2][2]/q integrator_reg[2][2]/Q -type DFF DFF
add mapped point integrator[2][4]/q integrator_reg[2][4]/Q -type DFF DFF
add mapped point integrator[2][5]/q integrator_reg[2][5]/Q -type DFF DFF
add mapped point integrator[2][6]/q integrator_reg[2][6]/Q -type DFF DFF
add mapped point integrator[2][7]/q integrator_reg[2][7]/Q -type DFF DFF
add mapped point integrator[2][8]/q integrator_reg[2][8]/Q -type DFF DFF
add mapped point integrator[2][9]/q integrator_reg[2][9]/Q -type DFF DFF
add mapped point integrator[2][10]/q integrator_reg[2][10]/Q -type DFF DFF
add mapped point integrator[2][12]/q integrator_reg[2][12]/Q -type DFF DFF
add mapped point integrator[2][13]/q integrator_reg[2][13]/Q -type DFF DFF
add mapped point integrator[2][14]/q integrator_reg[2][14]/Q -type DFF DFF
add mapped point integrator[1][13]/q integrator_reg[1][13]/Q -type DFF DFF
add mapped point integrator[2][17]/q integrator_reg[2][17]/Q -type DFF DFF
add mapped point integrator[2][18]/q integrator_reg[2][18]/Q -type DFF DFF
add mapped point integrator[3][0]/q integrator_reg[3][0]/Q -type DFF DFF
add mapped point integrator[3][1]/q integrator_reg[3][1]/Q -type DFF DFF
add mapped point integrator[3][2]/q integrator_reg[3][2]/Q -type DFF DFF
add mapped point integrator[3][3]/q integrator_reg[3][3]/Q -type DFF DFF
add mapped point integrator[3][4]/q integrator_reg[3][4]/Q -type DFF DFF
add mapped point integrator[3][5]/q integrator_reg[3][5]/Q -type DFF DFF
add mapped point integrator[3][6]/q integrator_reg[3][6]/Q -type DFF DFF
add mapped point integrator[3][8]/q integrator_reg[3][8]/Q -type DFF DFF
add mapped point integrator[3][9]/q integrator_reg[3][9]/Q -type DFF DFF
add mapped point integrator[3][10]/q integrator_reg[3][10]/Q -type DFF DFF
add mapped point integrator[3][12]/q integrator_reg[3][12]/Q -type DFF DFF
add mapped point integrator[3][13]/q integrator_reg[3][13]/Q -type DFF DFF
add mapped point integrator[3][14]/q integrator_reg[3][14]/Q -type DFF DFF
add mapped point integrator[3][16]/q integrator_reg[3][16]/Q -type DFF DFF
add mapped point integrator[3][17]/q integrator_reg[3][17]/Q -type DFF DFF
add mapped point integrator[3][18]/q integrator_reg[3][18]/Q -type DFF DFF
add mapped point integrator[3][19]/q integrator_reg[3][19]/Q -type DFF DFF
add mapped point d_comb[1][1][0]/q d_comb_reg[1][1][0]/Q -type DFF DFF
add mapped point d_comb[2][1][19]/q d_comb_reg[2][1][19]/Q -type DFF DFF
add mapped point d_comb[1][1][19]/q d_comb_reg[1][1][19]/Q -type DFF DFF
add mapped point d_comb[2][1][0]/q d_comb_reg[2][1][0]/Q -type DFF DFF
add mapped point d_comb[2][1][1]/q d_comb_reg[2][1][1]/Q -type DFF DFF
add mapped point d_comb[2][1][14]/q d_comb_reg[2][1][14]/Q -type DFF DFF
add mapped point d_comb[2][1][7]/q d_comb_reg[2][1][7]/Q -type DFF DFF
add mapped point d_comb[2][1][13]/q d_comb_reg[2][1][13]/Q -type DFF DFF
add mapped point d_comb[2][1][17]/q d_comb_reg[2][1][17]/Q -type DFF DFF
add mapped point d_comb[2][1][9]/q d_comb_reg[2][1][9]/Q -type DFF DFF
add mapped point d_comb[2][1][11]/q d_comb_reg[2][1][11]/Q -type DFF DFF
add mapped point d_comb[2][1][12]/q d_comb_reg[2][1][12]/Q -type DFF DFF
add mapped point d_comb[2][1][6]/q d_comb_reg[2][1][6]/Q -type DFF DFF
add mapped point d_comb[2][1][3]/q d_comb_reg[2][1][3]/Q -type DFF DFF
add mapped point d_comb[2][1][16]/q d_comb_reg[2][1][16]/Q -type DFF DFF
add mapped point d_comb[2][1][8]/q d_comb_reg[2][1][8]/Q -type DFF DFF
add mapped point d_comb[2][1][18]/q d_comb_reg[2][1][18]/Q -type DFF DFF
add mapped point d_comb[2][1][15]/q d_comb_reg[2][1][15]/Q -type DFF DFF
add mapped point d_comb[2][1][10]/q d_comb_reg[2][1][10]/Q -type DFF DFF
add mapped point d_comb[2][1][2]/q d_comb_reg[2][1][2]/Q -type DFF DFF
add mapped point d_comb[2][1][4]/q d_comb_reg[2][1][4]/Q -type DFF DFF
add mapped point d_comb[2][1][5]/q d_comb_reg[2][1][5]/Q -type DFF DFF
add mapped point d_comb[1][1][1]/q d_comb_reg[1][1][1]/Q -type DFF DFF
add mapped point d_comb[1][1][14]/q d_comb_reg[1][1][14]/Q -type DFF DFF
add mapped point d_comb[1][1][7]/q d_comb_reg[1][1][7]/Q -type DFF DFF
add mapped point d_comb[1][1][13]/q d_comb_reg[1][1][13]/Q -type DFF DFF
add mapped point d_comb[1][1][17]/q d_comb_reg[1][1][17]/Q -type DFF DFF
add mapped point d_comb[1][1][9]/q d_comb_reg[1][1][9]/Q -type DFF DFF
add mapped point d_comb[1][1][11]/q d_comb_reg[1][1][11]/Q -type DFF DFF
add mapped point d_comb[1][1][12]/q d_comb_reg[1][1][12]/Q -type DFF DFF
add mapped point d_comb[1][1][6]/q d_comb_reg[1][1][6]/Q -type DFF DFF
add mapped point d_comb[1][1][3]/q d_comb_reg[1][1][3]/Q -type DFF DFF
add mapped point d_comb[1][1][16]/q d_comb_reg[1][1][16]/Q -type DFF DFF
add mapped point d_comb[1][1][8]/q d_comb_reg[1][1][8]/Q -type DFF DFF
add mapped point d_comb[1][1][18]/q d_comb_reg[1][1][18]/Q -type DFF DFF
add mapped point d_comb[1][1][15]/q d_comb_reg[1][1][15]/Q -type DFF DFF
add mapped point d_comb[1][1][10]/q d_comb_reg[1][1][10]/Q -type DFF DFF
add mapped point d_comb[1][1][2]/q d_comb_reg[1][1][2]/Q -type DFF DFF
add mapped point d_comb[1][1][4]/q d_comb_reg[1][1][4]/Q -type DFF DFF
add mapped point d_comb[1][1][5]/q d_comb_reg[1][1][5]/Q -type DFF DFF
add mapped point d_comb[0][1][1]/q d_comb_reg[0][1][1]/Q -type DFF DFF
add mapped point d_comb[0][1][14]/q d_comb_reg[0][1][14]/Q -type DFF DFF
add mapped point d_comb[0][1][7]/q d_comb_reg[0][1][7]/Q -type DFF DFF
add mapped point d_comb[0][1][13]/q d_comb_reg[0][1][13]/Q -type DFF DFF
add mapped point d_comb[0][1][17]/q d_comb_reg[0][1][17]/Q -type DFF DFF
add mapped point d_comb[0][1][9]/q d_comb_reg[0][1][9]/Q -type DFF DFF
add mapped point d_comb[0][1][11]/q d_comb_reg[0][1][11]/Q -type DFF DFF
add mapped point d_comb[0][1][12]/q d_comb_reg[0][1][12]/Q -type DFF DFF
add mapped point d_comb[0][1][6]/q d_comb_reg[0][1][6]/Q -type DFF DFF
add mapped point d_comb[0][1][3]/q d_comb_reg[0][1][3]/Q -type DFF DFF
add mapped point d_comb[0][1][16]/q d_comb_reg[0][1][16]/Q -type DFF DFF
add mapped point d_tmp[0]/q d_tmp_reg[0]/Q -type DFF DFF
add mapped point d_comb[0][1][8]/q d_comb_reg[0][1][8]/Q -type DFF DFF
add mapped point d_comb[0][1][18]/q d_comb_reg[0][1][18]/Q -type DFF DFF
add mapped point d_comb[0][1][15]/q d_comb_reg[0][1][15]/Q -type DFF DFF
add mapped point d_comb[0][1][10]/q d_comb_reg[0][1][10]/Q -type DFF DFF
add mapped point d_comb[0][1][2]/q d_comb_reg[0][1][2]/Q -type DFF DFF
add mapped point d_comb[0][1][4]/q d_comb_reg[0][1][4]/Q -type DFF DFF
add mapped point d_comb[0][1][5]/q d_comb_reg[0][1][5]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
