###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID dtiresearch.iitbhu.ac.in)
#  Generated on:      Fri Feb  6 12:42:13 2026
#  Design:            cic
#  Command:           create_clock_tree_spec -out_file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Common UI
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_db clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_db port:clk .cts_is_sdc_clock_root true

# Clocks present at pin clk
#   clk (period 100.000ns) in timing_config func([./output_Feb06-12:16:56/cic_m.sdc])
create_clock_tree -name clk -source clk -no_skew_group
# Clock period setting for source pin of clk
set_db port:clk .cts_clock_period 100

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_db cts_timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:func (sdc ./output_Feb06-12:16:56/cic_m.sdc)
create_skew_group -name clk/func -sources clk -auto_sinks
set_db skew_group:clk/func .cts_skew_group_include_source_latency true
set_db skew_group:clk/func .cts_skew_group_created_from_clock clk
set_db skew_group:clk/func .cts_skew_group_created_from_constraint_mode func
set_db skew_group:clk/func .cts_skew_group_created_from_delay_corners {nom_nom fast_min}


check_clock_tree_convergence
# Restore the ILM status if possible
if { [get_db ccopt_auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

